local ADDON, CK = ...
_G.ControllerKeyboard = CK

CK.ADDON = ADDON
CK.Dicts = CK.Dicts or {}

---------------------------------------------------------------------------
-- Localisation: English is the base, each client language overrides it
---------------------------------------------------------------------------
local L = {
    SHIFT = "Shift",
    SYMBOLS = "123",
    LETTERS = "abc",
    SPACE = "Space",
    BACKSPACE = "Delete",
    SEND = "Send",
    SEND_COMBAT = "Keyboard opened in combat: press Enter to send.",
    DRAG_HINT = "Drag to move the keyboard (/ec lock to lock)",
    LOCKED = "Position locked: %s",
    TEXTURES_MISSING = "|cffff4040Textures not found|r: quit and restart the game (/reload is not enough for new files).",
    COMBAT_UNAVAILABLE = "Not possible in combat",
    HELP_PETAL = "Petal",
    HELP_LETTER = "Letter",
    HELP_CHANNEL = "Channel",
    HELP_PICK = "Select",
    HELP_CURSOR_L = "Left cursor",
    HELP_CURSOR_R = "Right cursor",
    HELP_TYPE_L = "Type left",
    HELP_TYPE_R = "Type right",
    OPT_INPUT = "Input",
    OPT_METHOD = "Input method",
    METHOD_WHEEL = "Daisywheel",
    METHOD_STICK = "Split keyboard",
    OPT_LAYOUT = "Layout (split keyboard)",
    OPT_DEADZONE = "Stick dead zone",
    OPT_MAGNET = "Magnet",
    OPT_CURVE = "Stick response",
    CURVE_LINEAR = "Linear",
    CURVE_GENTLE = "Gentle (precise near the center)",
    CURVE_FAST = "Fast",
    MAGNET_NONE = "None",
    MAGNET_WEAK = "Weak",
    MAGNET_MEDIUM = "Medium",
    MAGNET_STRONG = "Strong",
    OPT_LINE = "Show the cursor line",
    MODE_SET = "Input method: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Language: %s",
    REPLY_TO = "Reply to %s: ",
    WHISPER_NAME = "Whisper to (name, then A): ",
    CHANNEL_NAMES = { "Say", "Yell", "Party", "Raid", "Guild", "General (/1)", "Whisper", "Reply" },
    CHANNEL_UNAVAILABLE = "unavailable",
    BADGE_SHIFT = "SHIFT",
    BADGE_CAPS = "CAPS",
    FONT_CHAT = "Chat font",
    GLYPHS_NONE = "No gamepad button atlas found: the addon's glyphs are used.",
    GLYPHS_FOUND = "%d gamepad button atlases found:",
    OPT_SUBTITLE = "On-screen keyboard to type in chat with a gamepad or the mouse.",
    OPT_KEYBOARD = "Keyboard",
    OPT_LOCK = "Lock position",
    OPT_AUTO = "Open automatically with the chat",
    OPT_PAD_ONLY = "Only when the gamepad is active",
    OPT_INVERT = "Invert the sticks vertical axis",
    OPT_SCALE = "Keyboard size",
    SIZE_SMALL = "Small",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Large",
    SIZE_XL = "Extra large",
    OPT_ACTIONS = "Show the mouse buttons (Shift, 123, Space, Delete, Send, X)",
    OPT_STICKY = "The chosen channel becomes the chat's own (like typing /p in game)",
    OPT_LOOK = "Look",
    OPT_FONT = "Font",
    OPT_GLYPHS = "Button glyphs",
    OPT_GAME_GLYPHS = "Use the game's button icons when available",
    OPT_PREDICTION = "Prediction",
    OPT_LANG = "Suggestion language",
    OPT_LEARN = "Learn from my messages",
    OPT_RESET_POS = "Reset keyboard position",
    OPT_FORGET = "Forget learned words",
    OPT_FORGET_CONFIRM = "Click again to confirm",
    LOADED = "v%s loaded. /ec for help.",
    WHEEL_NOTHING = "Aim at a slot",
    WHEEL_NOTHING_HINT = "In the middle, A closes without using anything",
    WHEEL_LOCK = "Lock the position (unlocked: drag the open wheel with the mouse)",
    WHEEL_MOVE = "Move the wheel with the D-pad",
    WHEEL_RESET = "Back to the middle of the screen",
    CFG_TAB_WHEEL = "Wheel",
    WHEEL_NAME = "Consumables wheel",
    WHEEL_ENABLE = "Use the consumables wheel",
    WHEEL_INFO = "Give it a key: Gamepad tab, Items list (any free button or paddle, in any layer), or Escape > Key Bindings > AddOns.",
    WHEEL_INFO2 = "Open: the right stick or the D-pad picks, A uses, B closes; the mouse clicks a slot. Works in combat (food and drink greyed there).",
    WHEEL_VARIANTS = "Every variant you carry, after the best of each kind (up to 12 slots)",
    WHEEL_H_CATEGORIES = "In the wheel",
    WHEEL_CAT_FOOD = "Food",
    WHEEL_CAT_DRINK = "Drink",
    WHEEL_CAT_HEALTHPOTION = "Healing potions",
    WHEEL_CAT_MANAPOTION = "Mana potions",
    WHEEL_CAT_HEALTHSTONE = "Healthstone",
    WHEEL_CAT_MANAGEM = "Mana gem",
    WHEEL_CAT_BANDAGE = "Bandages (on yourself)",
    WHEEL_CAT_BUFFFOOD = "Buff food (well fed)",
    WHEEL_CAT_ELIXIR = "Elixirs, flasks and other potions",
    WHEEL_CAT_SCROLL = "Scrolls",
    WHEEL_AIM = "Pick",
    WHEEL_USE = "Use",
    WHEEL_CLOSE = "Close",
    CFG_TAB_SUPPLIES = "Supplies",
    SUP_ENABLE = "Show the supplies buttons",
    SUP_INFO = "One round button per resource. Under its low threshold it glows, stronger down to the critical one (red). A click opens the bags.",
    SUP_LOCK = "Lock the position (unlocked: drag the buttons with the mouse)",
    SUP_MOVE = "Move with the D-pad",
    SUP_RESET = "Back to the default place",
    SUP_LAYOUT = "Direction of the buttons",
    SUP_DIR_RIGHT = "Towards the right",
    SUP_DIR_LEFT = "Towards the left",
    SUP_DIR_DOWN = "Downwards",
    SUP_DIR_UP = "Upwards",
    SUP_SIZE = "Button size",
    SUP_H_TRACKED = "Tracked resources",
    SUP_LOW = "Low threshold",
    SUP_CRITICAL = "Critical threshold",
    SUP_REMOVE = "Remove from the list",
    SUP_H_ADD = "Add an item from your bags",
    SUP_ADD_SHOW = "Pick an item of your bags to track",
    SUP_ADD_HIDE = "Hide the list of items",
    SUP_ADD_NONE = "Nothing else in your bags.",
    SUP_BAGS = "Free bag slots",
    SUP_AMMO = "Ammunition",
    SUP_TIP_COUNT = "Left: %d",
    SUP_TIP_THRESHOLDS = "Low: %d, critical: %d",
    SUP_TIP_CLICK = "Click: open the bags",
    CFG_TAB_VIBRATION = "Vibrations",
    CFG_TEST = "Test",
    CFG_P_TOGGLE = "On / off",
    VIB_OFF = "Off",
    CFG_P_PATTERN = "Pattern / off",
    VIB_ENABLE = "Vibrate the controller",
    VIB_OFF_INFO = "Vibrations are off: no event makes the controller vibrate.",
    VIB_INTENSITY = "Intensity (all vibrations)",
    VIB_INFO = "Each event: the D-pad picks its pattern or Off, A tests it, X turns it on or off.",
    VIB_UNAVAILABLE = "unavailable",
    VIB_UNAVAILABLE_TIP = "WoW Forever hides your exact health from addons in combat: this vibration cannot work on this client.",
    VIB_H_COMBAT = "Combat",
    VIB_H_SOCIAL = "Social",
    VIB_H_PROGRESS = "Progress",
    VIB_H_ADDON = "Easy Controller",
    VIB_P_MICRO = "Micro tick",
    VIB_P_TICK = "Tick",
    VIB_P_DOUBLE = "Double tick",
    VIB_P_PULSE = "Pulse",
    VIB_P_LONG = "Long",
    VIB_P_HEART = "Heartbeat",
    VIB_P_RISE = "Crescendo",
    VIB_E_LOWHEALTH = "Low health (below 35 %, faster below 20 %)",
    VIB_E_BIGHIT = "Big hit taken (over 10 % of your health)",
    VIB_E_DEATH = "Death",
    VIB_E_INTERRUPTED = "Your spell is interrupted",
    VIB_E_LOSSOFCONTROL = "Loss of control (stun, fear, silence…)",
    VIB_E_AGGRO = "You gain aggro",
    VIB_E_COMBAT = "Entering combat",
    VIB_E_PROC = "Spell proc (highlight)",
    VIB_E_ACTIONFAILED = "Action impossible (range, mana, target…)",
    VIB_E_WHISPER = "Whisper received",
    VIB_E_INVITE = "Group or raid invite",
    VIB_E_READYCHECK = "Ready check",
    VIB_E_REZSUMMON = "Resurrection or summon offered",
    VIB_E_TRADEDUEL = "Trade or duel request",
    VIB_E_LEVELUP = "Level up",
    VIB_E_QUEST = "Quest objective or quest complete",
    VIB_E_RARELOOT = "Rare loot or better",
    VIB_E_BAGSFULL = "Bags full (game message)",
    VIB_E_DURABILITY = "Gear almost broken",
    VIB_E_LOWSTOCK = "Low supplies (ammo, shards…)",
    VIB_E_LOWSPACE = "Little room left in the bags",
    VIB_E_WHEELTICK = "Wheel: moving from slot to slot",
    VIB_E_KEYPRESS = "Chat keyboard: key typed",
    VIB_DIAG = "Vibration API: %s, controller: %s, your health: %s, vibrations on: %s",
    VIB_DIAG_HIDDEN = "hidden by the game",
    VIB_DIAG_PATTERNS = "Patterns: %s",
    OLD_FOLDER = "|cffff6060The old ControllerKeyboard folder is still installed and loads too.|r Delete Interface/AddOns/ControllerKeyboard (game closed): Easy Controller now lives in EasyController.",
    HELP = {
        "/ec - open the keyboard",
        "/ec auto - open automatically with the chat (current: %s)",
        "/ec pad - only auto-open when the gamepad is active (current: %s)",
        "/ec learn - learn words from your messages (current: %s)",
        "/ec lock - lock/unlock the position (current: %s)",
        "/ec mode wheel|stick - daisywheel or split keyboard",
        "/ec layout azerty|qwerty|qwertz|es|it - split keyboard layout",
        "/ec lang fr|en|de|es|it|both - suggestion and accent language",
        "/ec scale 0.8 - keyboard size",
        "/ec invert - invert the stick vertical axis",
        "/ec reset - reset keyboard position",
        "/ec stats - learning statistics",
        "/ec forget - forget all learned words",
        "/ec glyphs - list the game's gamepad button icons",
        "/ec config - configuration (also RB + D-pad down)",
        "/ec map - gamepad mapping (free buttons, back paddles)",
        "/ec keys - show the keys the game receives (back paddles)",
        "/ec vibe [pattern] - test the controller vibration",
        "/ec debug - print received buttons",
        "Options: Escape > Options > AddOns > Easy Controller - Forever",
    },
    ON = "|cff40ff40on|r",
    OFF = "|cffff4040off|r",
    STATS = "%d learned words, %d dictionary words.",
    FORGOT = "Learned words cleared.",
    FORGET_CONFIRM = "Type /ec forget confirm to clear all learned words.",
    NO_DICT = "Dictionary not available: %s",
    BINDING_TOGGLE = "Toggle keyboard",
    BADGE_HIDDEN = "Hidden",
    BADGE_RIGHT = "Right",
    BADGE_LEFT = "Left",
    BADGE_BOTTOM = "Below",
    BADGE_TOP = "Above",
    BADGE_OUTER = "Outer side (left / right)",
    BADGE_OUTER_V = "Outer side (up / down)",
    OPT_BADGE = "Name of the extra buttons (R4...)",
    PLACE_MOVING = "moving",
    PLACE_P_CANCEL = "Cancel",
    PLACE_P_DROP = "Put down",
    PLACE_P_GRAB = "Pick up",
    PLACE_P_SELECT = "Select",
    MAP_SLOT_HINT = "A slot of the game's gamepad bar: A to put a spell, an item or a macro in it (like the game's own editor), X to empty it.",
    FEAT_RT_MODIFIER = "RT acts as a modifier: game functions on RT + paddles too",
    FEAT_RT_MODIFIER_TIP = "Without it, RT + a paddle takes spells, items and macros. With it (the game's gamepad setting \"RT emulates Alt\", or Ctrl, like LT already sends Shift), RT + a paddle is a key of its own and takes game functions too. The game's own RT bar still works.",
    FEAT_QUEST_GLOW = "Orange border on quest objective items in the bags (those the game does not mark)",
    MAP_P_CONFIRM = "Confirm",
    PLACE_BAR = "Gamepad bar",
    PLACE_P_PLACE = "Place",
    FEAT_SHOW_STICKS = "Show L3 and R3 next to the bar, with what they do (autorun, ping...)",
    FEAT_SHORTCUT = "Gamepad shortcut to open this panel",
    CFG_SHORTCUT_KEY = "Combination: %s (A to change)",
    CFG_SHORTCUT_PRESS = "Hold a button and press a second one... (Escape or B alone: cancel)",
    CFG_SHORTCUT_RESET = "Back to %s",
    CFG_TAB_GENERAL = "General",
    CFG_TAB_KEYBOARD = "Keyboard",
    CFG_TAB_GAMEPAD = "Gamepad",
    CFG_P_CHANGE = "Change",
    CFG_OPEN = "Open the configuration",
    CFG_OPEN_LATER = "The Easy Controller - Forever panel opens once you are back in the game (options and game menu closed).",
    CFG_SETTINGS_HINT = "Every setting is in the addon's own panel, driven with the gamepad or the mouse: RB + D-pad down, /ec config, or its key binding.",
    CFG_H_FEATURES = "Features",
    FEAT_DRAFTS = "Keep the message as a draft when the game closes the chat",
    FEAT_LINKS = "Add Shift+click and \"Share in chat\" links to the message",
    FEAT_QUEST_TOOLTIP = "Orange \"do not sell\" line in item tooltips",
    FEAT_QUEST_SELL = "Warning when a quest item is sold",
    FEAT_QUEST_HOVER = "Warning when a quest item is selected at a merchant (gamepad bags without tooltips)",
    FEAT_EXTRA_DISPLAY = "Show the extra buttons next to the gamepad action bar",
    MAP_IDENTIFY = "Identify the back paddles",
    MAP_IDENTIFY_HINT = "Press each back paddle when asked, to tell the addon which key or button it sends (set the paddles to keyboard keys in Steam Input first).",
    MAP_PLACE = "Place the bar and extra buttons",
    MAP_PLACE_HINT = "Move the game's gamepad bar by steps, and place each extra button (back paddles, L3, R3) around it, on the screen.",
    MAP_WIZARD = "Press the back paddle %s now.",
    MAP_WIZARD_DONE = "Back paddles identified.",
    MAP_P_SKIP = "Skip",
    MAP_P_SECTION = "Section",
    MAP_P_LIST = "List",
    PLACE_TITLE = "Place the bar and extra buttons",
    PLACE_P_BUTTON = "Element",
    PLACE_P_SYM = "Mirror: %s",
    PLACE_P_RESET = "Default place",
    PLACE_P_DONE = "Done",
    BINDING_CONFIG = "Easy Controller - Forever configuration",
    MOD_MAPPING = "Gamepad: extra functions on the free buttons and back paddles",
    MAP_TITLE = "Gamepad mapping",
    MAP_ALONE = "Alone",
    MAP_FREE = "Free",
    MAP_GAME = "Game",
    MAP_EMPTY_SLOT = "empty",
    MAP_BACK_ROW = "Back paddles",
    MAP_LOCKED = "No layer here: this trigger is not a modifier in the game's gamepad settings, the button does the same as without it.",
    MAP_SHARED_HINT = "Same key as without the trigger (not a modifier): spells, items and macros. For game functions, make RT a modifier (General tab).",
    MAP_SHARED_LOCKED = "Same key as %s, which runs a game function (%s): a game function takes the key in all its layers. Put a spell, an item or a macro there instead, or make RT a modifier (General tab).",
    MAP_SHARED_INACTIVE = "Not active: a game function needs a key of its own, and this layer shares the paddle's key (the trigger is no modifier). Make RT a modifier (General tab), or choose a spell, an item or a macro.",
    MAP_NATIVE_HINT = "Fixed by the game, left as it is.",
    MAP_FREE_HINT = "Free: A to give it a function.",
    MAP_ASSIGNED_HINT = "Added by Easy Controller (X to remove).",
    MAP_PADDLE_KEY = "Paddle key: %s (Y to learn it again)",
    MAP_PADDLE_PRESS = "Press the paddle now... (B to cancel)",
    MAP_NOTHING = "Nothing here",
    MAP_TAB_GAME = "Game",
    MAP_TAB_SPELLS = "Spells",
    MAP_TAB_ITEMS = "Items",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Bar",
    MAP_P_MOVE = "Move",
    MAP_P_CHOOSE = "Choose",
    MAP_P_CLEAR = "Remove",
    MAP_P_KEY = "Paddle key",
    MAP_P_LAYER = "Layer",
    MAP_P_CLOSE = "Close",
    MAP_P_BACK = "Back",
    MAP_P_TAB = "Tab",
    NAT_JUMP = "Jump",
    NAT_INTERACT = "Interact",
    NAT_BACK = "Back",
    NAT_INSPECT = "Inspect",
    NAT_TARGET_FRIEND = "Target allies",
    NAT_TARGET_ENEMY = "Target enemies",
    NAT_LAYER_LEFT = "Left bar",
    NAT_LAYER_RIGHT = "Right bar",
    NAT_START = "Start menu",
    NAT_SELECT = "Interface focus",
    NAT_PING = "Ping",
    BINDING_MAP = "Gamepad mapping",
    PADDLE_KEY_REPLACES = "%s was bound to \"%s\": the paddle takes it over.",
    CAT_COMMON = "Common shortcuts",
    DETECT_START = "Press each back paddle (L4, R4, L5, R5) now: the keys received are listed for %d seconds.",
    DETECT_KEY = "Key received: %s",
    DETECT_PAD = "Gamepad button received: %s",
    DETECT_END = "Key detection over.",
    QUEST_ITEM_TIP = "Quest item: do not sell",
    QUEST_ITEM_FOR = "Quest item (%s): do not sell",
    QUEST_ITEM_SOLD = "Quest item sold: %s. Buy it back from the merchant's Buyback tab.",
    QUEST_ITEM_SOLD_SHORT = "Quest item sold! See the Buyback tab",
    NO_QUESTS = "No quest in progress",
    QUESTS_TIP = "Quests: insert a quest link",
    KEYBOARD_OFF = "The keyboard is turned off (Options > AddOns > Easy Controller - Forever > Modules).",
    MOD_KEYBOARD = "Keyboard (daisywheel / split keyboard)",
    MOD_QUEST_ITEMS = "Quest items: \"do not sell\" in tooltips, warning at merchants",
    MOD_QUEST_LINKS = "Quest links in the keyboard (and Shift+click links)",
}
CK.L = L

local LOCALES = {}

LOCALES.frFR = {
    SHIFT = "Maj",
    SPACE = "Espace",
    BACKSPACE = "Effacer",
    SEND = "Envoyer",
    SEND_COMBAT = "Clavier ouvert en combat : appuyez sur Entrée pour envoyer.",
    DRAG_HINT = "Glisser pour déplacer le clavier (/ec lock pour verrouiller)",
    LOCKED = "Position verrouillée : %s",
    TEXTURES_MISSING = "|cffff4040Textures introuvables|r : quittez et relancez le jeu (un /reload ne suffit pas pour de nouveaux fichiers).",
    COMBAT_UNAVAILABLE = "Impossible en combat",
    HELP_PETAL = "Pétale",
    HELP_LETTER = "Lettre",
    HELP_CHANNEL = "Canal",
    HELP_PICK = "Choisir",
    HELP_CURSOR_L = "Curseur G",
    HELP_CURSOR_R = "Curseur D",
    HELP_TYPE_L = "Taper G",
    HELP_TYPE_R = "Taper D",
    OPT_INPUT = "Saisie",
    OPT_METHOD = "Méthode de saisie",
    METHOD_STICK = "Clavier 2 sticks",
    OPT_LAYOUT = "Disposition (clavier 2 sticks)",
    OPT_DEADZONE = "Zone morte du stick",
    OPT_MAGNET = "Effet aimant",
    OPT_CURVE = "Réponse du stick",
    CURVE_LINEAR = "Linéaire",
    CURVE_GENTLE = "Douce (précise au centre)",
    CURVE_FAST = "Rapide",
    MAGNET_NONE = "Aucun",
    MAGNET_WEAK = "Faible",
    MAGNET_MEDIUM = "Moyen",
    MAGNET_STRONG = "Fort",
    OPT_LINE = "Afficher la ligne du curseur",
    MODE_SET = "Méthode de saisie : %s",
    LAYOUT_SET = "Disposition : %s",
    LANG_SET = "Langue : %s",
    REPLY_TO = "Répondre à %s : ",
    WHISPER_NAME = "Chuchoter à (nom, puis A) : ",
    CHANNEL_NAMES = { "Dire", "Crier", "Groupe", "Raid", "Guilde", "Général (/1)", "Chuchoter", "Répondre" },
    CHANNEL_UNAVAILABLE = "indisponible",
    BADGE_SHIFT = "MAJ",
    BADGE_CAPS = "VERR. MAJ",
    FONT_CHAT = "Police du chat",
    GLYPHS_NONE = "Aucun atlas de boutons manette trouvé : les glyphes de l'addon sont utilisés.",
    GLYPHS_FOUND = "%d atlas de boutons manette trouvés :",
    OPT_SUBTITLE = "Clavier à l'écran pour écrire dans le chat à la manette ou à la souris.",
    OPT_KEYBOARD = "Clavier",
    OPT_LOCK = "Verrouiller la position",
    OPT_AUTO = "Ouvrir automatiquement avec le chat",
    OPT_PAD_ONLY = "Seulement quand la manette est active",
    OPT_INVERT = "Inverser l'axe vertical des sticks",
    OPT_SCALE = "Taille du clavier",
    SIZE_SMALL = "Petite",
    SIZE_NORMAL = "Normale",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Très grande",
    OPT_ACTIONS = "Afficher les boutons souris (Maj, 123, Espace, Effacer, Envoyer, X)",
    OPT_STICKY = "Le canal choisi devient celui du chat (comme taper /p en jeu)",
    OPT_LOOK = "Apparence",
    OPT_FONT = "Police",
    OPT_GLYPHS = "Boutons affichés",
    OPT_GAME_GLYPHS = "Utiliser les icônes de boutons du jeu si disponibles",
    OPT_PREDICTION = "Prédiction",
    OPT_LANG = "Langue des suggestions",
    OPT_LEARN = "Apprendre de mes messages",
    OPT_RESET_POS = "Replacer le clavier",
    OPT_FORGET = "Oublier les mots appris",
    OPT_FORGET_CONFIRM = "Cliquer pour confirmer",
    LOADED = "v%s chargé. /ec pour l'aide.",
    WHEEL_NOTHING = "Visez une case",
    WHEEL_NOTHING_HINT = "Au centre, A ferme sans rien utiliser",
    WHEEL_LOCK = "Verrouiller la position (déverrouillée : glisser la roue ouverte à la souris)",
    WHEEL_MOVE = "Déplacer la roue à la croix",
    WHEEL_RESET = "Remettre au centre de l'écran",
    CFG_TAB_WHEEL = "Roue",
    WHEEL_NAME = "Roue des consommables",
    WHEEL_ENABLE = "Utiliser la roue des consommables",
    WHEEL_INFO = "Donnez-lui une touche : onglet Manette, liste Objets (tout bouton libre ou palette, dans toute couche), ou Échap > Raccourcis > AddOns.",
    WHEEL_INFO2 = "Ouverte : le stick droit ou la croix choisit, A utilise, B ferme ; la souris clique une case. Marche en combat (nourriture et boisson grisées).",
    WHEEL_VARIANTS = "Toutes les variantes portées, après la meilleure de chaque type (jusqu'à 12 cases)",
    WHEEL_H_CATEGORIES = "Dans la roue",
    WHEEL_CAT_FOOD = "Nourriture",
    WHEEL_CAT_DRINK = "Boisson",
    WHEEL_CAT_HEALTHPOTION = "Potions de soins",
    WHEEL_CAT_MANAPOTION = "Potions de mana",
    WHEEL_CAT_HEALTHSTONE = "Pierre de soins",
    WHEEL_CAT_MANAGEM = "Gemme de mana",
    WHEEL_CAT_BANDAGE = "Bandages (sur vous)",
    WHEEL_CAT_BUFFFOOD = "Nourriture de buff (bien nourri)",
    WHEEL_CAT_ELIXIR = "Élixirs, flacons et autres potions",
    WHEEL_CAT_SCROLL = "Parchemins",
    WHEEL_AIM = "Choisir",
    WHEEL_USE = "Utiliser",
    WHEEL_CLOSE = "Fermer",
    CFG_TAB_SUPPLIES = "Réserves",
    SUP_ENABLE = "Afficher les boutons de réserves",
    SUP_INFO = "Un bouton rond par ressource. Sous son seuil bas il s'illumine, de plus en plus fort jusqu'au seuil critique (rouge). Un clic ouvre les sacs.",
    SUP_LOCK = "Verrouiller la position (déverrouillée : glisser les boutons à la souris)",
    SUP_MOVE = "Déplacer à la croix",
    SUP_RESET = "Remettre à la place par défaut",
    SUP_LAYOUT = "Sens des boutons",
    SUP_DIR_RIGHT = "Vers la droite",
    SUP_DIR_LEFT = "Vers la gauche",
    SUP_DIR_DOWN = "Vers le bas",
    SUP_DIR_UP = "Vers le haut",
    SUP_SIZE = "Taille des boutons",
    SUP_H_TRACKED = "Ressources suivies",
    SUP_LOW = "Seuil bas",
    SUP_CRITICAL = "Seuil critique",
    SUP_REMOVE = "Retirer de la liste",
    SUP_H_ADD = "Ajouter un objet de vos sacs",
    SUP_ADD_SHOW = "Choisir un objet de vos sacs à suivre",
    SUP_ADD_HIDE = "Masquer la liste des objets",
    SUP_ADD_NONE = "Rien d'autre dans vos sacs.",
    SUP_BAGS = "Places libres dans les sacs",
    SUP_AMMO = "Munitions",
    SUP_TIP_COUNT = "Reste : %d",
    SUP_TIP_THRESHOLDS = "Bas : %d, critique : %d",
    SUP_TIP_CLICK = "Clic : ouvrir les sacs",
    CFG_TAB_VIBRATION = "Vibrations",
    CFG_TEST = "Tester",
    CFG_P_TOGGLE = "Activer / désactiver",
    VIB_OFF = "Désactivé",
    CFG_P_PATTERN = "Motif / désactivé",
    VIB_ENABLE = "Faire vibrer la manette",
    VIB_OFF_INFO = "Vibrations désactivées : aucun événement ne fait vibrer la manette.",
    VIB_INTENSITY = "Intensité (toutes les vibrations)",
    VIB_INFO = "Chaque événement : la croix choisit son motif ou « Désactivé », A le teste, X l'active ou le désactive.",
    VIB_UNAVAILABLE = "indisponible",
    VIB_UNAVAILABLE_TIP = "WoW Forever cache aux addons votre vie exacte en combat : cette vibration ne peut pas fonctionner sur ce client.",
    VIB_H_COMBAT = "Combat",
    VIB_H_SOCIAL = "Social",
    VIB_H_PROGRESS = "Progression",
    VIB_H_ADDON = "Easy Controller",
    VIB_P_MICRO = "Micro-tic",
    VIB_P_TICK = "Tic",
    VIB_P_DOUBLE = "Double tic",
    VIB_P_PULSE = "Impulsion",
    VIB_P_LONG = "Longue",
    VIB_P_HEART = "Battement de cœur",
    VIB_P_RISE = "Crescendo",
    VIB_E_LOWHEALTH = "Vie basse (sous 35 %, plus rapide sous 20 %)",
    VIB_E_BIGHIT = "Gros coup reçu (plus de 10 % de la vie)",
    VIB_E_DEATH = "Mort",
    VIB_E_INTERRUPTED = "Votre sort est interrompu",
    VIB_E_LOSSOFCONTROL = "Perte de contrôle (étourdi, peur, silence…)",
    VIB_E_AGGRO = "Vous prenez l'aggro",
    VIB_E_COMBAT = "Entrée en combat",
    VIB_E_PROC = "Proc d'un sort (surbrillance)",
    VIB_E_ACTIONFAILED = "Action impossible (portée, mana, cible…)",
    VIB_E_WHISPER = "Chuchotement reçu",
    VIB_E_INVITE = "Invitation de groupe ou de raid",
    VIB_E_READYCHECK = "Appel (ready check)",
    VIB_E_REZSUMMON = "Résurrection ou invocation proposée",
    VIB_E_TRADEDUEL = "Demande d'échange ou de duel",
    VIB_E_LEVELUP = "Montée de niveau",
    VIB_E_QUEST = "Objectif ou quête terminé",
    VIB_E_RARELOOT = "Butin rare ou mieux",
    VIB_E_BAGSFULL = "Sacs pleins (message du jeu)",
    VIB_E_DURABILITY = "Équipement presque cassé",
    VIB_E_LOWSTOCK = "Stock bas (munitions, fragments…)",
    VIB_E_LOWSPACE = "Peu de place dans les sacs",
    VIB_E_WHEELTICK = "Roue : passage d'une case à l'autre",
    VIB_E_KEYPRESS = "Clavier de chat : touche tapée",
    VIB_DIAG = "API de vibration : %s, manette : %s, votre vie : %s, vibrations activées : %s",
    VIB_DIAG_HIDDEN = "masquée par le jeu",
    VIB_DIAG_PATTERNS = "Motifs : %s",
    OLD_FOLDER = "|cffff6060L'ancien dossier ControllerKeyboard est encore installé et se charge aussi.|r Supprimez Interface/AddOns/ControllerKeyboard (jeu fermé) : Easy Controller est maintenant dans EasyController.",
    HELP = {
        "/ec - ouvrir le clavier",
        "/ec auto - ouverture automatique avec le chat (actuel : %s)",
        "/ec pad - n'ouvrir automatiquement que si la manette est active (actuel : %s)",
        "/ec learn - apprendre les mots de vos messages (actuel : %s)",
        "/ec lock - verrouiller/déverrouiller la position (actuel : %s)",
        "/ec mode wheel|stick - daisywheel ou clavier 2 sticks",
        "/ec layout azerty|qwerty|qwertz|es|it - disposition du clavier 2 sticks",
        "/ec lang fr|en|de|es|it|both - langue des suggestions et des accents",
        "/ec scale 0.8 - taille du clavier",
        "/ec invert - inverser l'axe vertical du stick",
        "/ec reset - replacer le clavier",
        "/ec stats - statistiques d'apprentissage",
        "/ec forget - oublier tous les mots appris",
        "/ec glyphs - lister les icônes de boutons manette du jeu",
        "/ec config - configuration (aussi RB + croix bas)",
        "/ec map - mappage manette (touches libres, palettes)",
        "/ec keys - afficher les touches reçues par le jeu (palettes)",
        "/ec vibe [motif] - tester la vibration de la manette",
        "/ec debug - afficher les boutons reçus",
        "Options : Échap > Options > AddOns > Easy Controller - Forever",
    },
    ON = "|cff40ff40oui|r",
    OFF = "|cffff4040non|r",
    STATS = "%d mots appris, %d mots dans le dictionnaire.",
    FORGOT = "Mots appris effacés.",
    FORGET_CONFIRM = "Tapez /ec forget confirm pour effacer tous les mots appris.",
    NO_DICT = "Dictionnaire indisponible : %s",
    BINDING_TOGGLE = "Ouvrir/fermer le clavier",
    BADGE_HIDDEN = "Masqué",
    BADGE_RIGHT = "À droite",
    BADGE_LEFT = "À gauche",
    BADGE_BOTTOM = "En dessous",
    BADGE_TOP = "Au-dessus",
    BADGE_OUTER = "Côté extérieur (gauche/droite)",
    BADGE_OUTER_V = "Côté extérieur (haut/bas)",
    OPT_BADGE = "Nom des touches en plus (R4...)",
    PLACE_MOVING = "en déplacement",
    PLACE_P_CANCEL = "Annuler",
    PLACE_P_DROP = "Poser",
    PLACE_P_GRAB = "Prendre",
    PLACE_P_SELECT = "Choisir",
    MAP_SLOT_HINT = "Case de la barre manette du jeu : A pour y placer un sort, un objet ou une macro (comme l'éditeur du jeu), X pour la vider.",
    FEAT_RT_MODIFIER = "RT agit comme modificateur : fonctions du jeu aussi sur RT + palettes",
    FEAT_RT_MODIFIER_TIP = "Sans cela, RT + une palette prend les sorts, objets et macros. Avec (le paramètre manette du jeu « RT émule Alt », ou Ctrl, comme LT envoie déjà Maj), RT + une palette devient une touche à part et prend aussi les fonctions du jeu. La barre RT du jeu fonctionne toujours.",
    FEAT_QUEST_GLOW = "Liseré orange sur les objets à collecter pour une quête dans les sacs (ceux que le jeu ne marque pas)",
    MAP_P_CONFIRM = "Valider",
    PLACE_BAR = "Barre manette",
    PLACE_P_PLACE = "Place",
    FEAT_SHOW_STICKS = "Afficher L3 et R3 près de la barre, avec leur action (course auto, ping...)",
    FEAT_SHORTCUT = "Raccourci manette pour ouvrir ce panneau",
    CFG_SHORTCUT_KEY = "Combinaison : %s (A pour changer)",
    CFG_SHORTCUT_PRESS = "Maintenez un bouton et appuyez sur un second... (Échap ou B seul : annuler)",
    CFG_SHORTCUT_RESET = "Revenir à %s",
    CFG_TAB_GENERAL = "Général",
    CFG_TAB_KEYBOARD = "Clavier",
    CFG_TAB_GAMEPAD = "Manette",
    CFG_P_CHANGE = "Changer",
    CFG_OPEN = "Ouvrir la configuration",
    CFG_OPEN_LATER = "Le panneau Easy Controller - Forever s'ouvrira quand vous serez revenu en jeu (options et menu du jeu fermés).",
    CFG_SETTINGS_HINT = "Tous les réglages sont dans le panneau de l'addon, à la manette ou à la souris : RB + croix bas, /ec config ou son raccourci.",
    CFG_H_FEATURES = "Fonctions",
    FEAT_DRAFTS = "Garder le message en brouillon quand le jeu ferme le chat",
    FEAT_LINKS = "Ajouter au message les liens Maj+clic et « Partager dans la discussion »",
    FEAT_QUEST_TOOLTIP = "Ligne orange « ne pas vendre » dans les info-bulles",
    FEAT_QUEST_SELL = "Alerte quand un objet de quête est vendu",
    FEAT_QUEST_HOVER = "Alerte en sélectionnant un objet de quête chez un marchand (sacs manette sans info-bulles)",
    FEAT_EXTRA_DISPLAY = "Afficher les touches en plus à côté de la barre d'action manette",
    MAP_IDENTIFY = "Identifier les palettes arrière",
    MAP_IDENTIFY_HINT = "Appuyez sur chaque palette quand elle est demandée, pour que l'addon sache quelle touche ou quel bouton elle envoie (assignez d'abord des touches clavier aux palettes dans Steam Input).",
    MAP_PLACE = "Placer la barre et les touches",
    MAP_PLACE_HINT = "Déplacez la barre manette du jeu par crans, et placez chaque touche en plus (palettes, L3, R3) autour, directement à l'écran.",
    MAP_WIZARD = "Appuyez maintenant sur la palette %s.",
    MAP_WIZARD_DONE = "Palettes arrière identifiées.",
    MAP_P_SKIP = "Passer",
    MAP_P_SECTION = "Section",
    MAP_P_LIST = "Liste",
    PLACE_TITLE = "Placer la barre et les touches",
    PLACE_P_BUTTON = "Élément",
    PLACE_P_SYM = "Symétrie : %s",
    PLACE_P_RESET = "Place par défaut",
    PLACE_P_DONE = "Terminer",
    BINDING_CONFIG = "Configuration de Easy Controller - Forever",
    MOD_MAPPING = "Manette : fonctions en plus sur les touches libres et les palettes arrière",
    MAP_TITLE = "Mappage manette",
    MAP_ALONE = "Seul",
    MAP_FREE = "Libre",
    MAP_GAME = "Jeu",
    MAP_EMPTY_SLOT = "vide",
    MAP_BACK_ROW = "Palettes arrière",
    MAP_LOCKED = "Pas de couche ici : cette gâchette n'est pas un modificateur dans les réglages manette du jeu, le bouton fait la même chose que sans elle.",
    MAP_SHARED_HINT = "Même touche que sans la gâchette (pas un modificateur) : sorts, objets et macros. Pour les fonctions du jeu, faites de RT un modificateur (onglet Général).",
    MAP_SHARED_LOCKED = "Même touche que %s, qui lance une fonction du jeu (%s) : une fonction du jeu prend la touche dans toutes ses couches. Mettez-y plutôt un sort, un objet ou une macro, ou faites de RT un modificateur (onglet Général).",
    MAP_SHARED_INACTIVE = "Inactive : une fonction du jeu a besoin d'une touche à elle, et cette couche partage la touche de la palette (la gâchette n'est pas un modificateur). Faites de RT un modificateur (onglet Général), ou choisissez un sort, un objet ou une macro.",
    MAP_NATIVE_HINT = "Fonction fixe du jeu, laissée telle quelle.",
    MAP_FREE_HINT = "Libre : A pour lui donner une fonction.",
    MAP_ASSIGNED_HINT = "Ajouté par Easy Controller (X pour retirer).",
    MAP_PADDLE_KEY = "Touche de la palette : %s (Y pour la réapprendre)",
    MAP_PADDLE_PRESS = "Appuyez maintenant sur la palette... (B pour annuler)",
    MAP_NOTHING = "Rien ici",
    MAP_TAB_GAME = "Jeu",
    MAP_TAB_SPELLS = "Sorts",
    MAP_TAB_ITEMS = "Objets",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Barre",
    MAP_P_MOVE = "Déplacer",
    MAP_P_CHOOSE = "Choisir",
    MAP_P_CLEAR = "Retirer",
    MAP_P_KEY = "Touche palette",
    MAP_P_LAYER = "Couche",
    MAP_P_CLOSE = "Fermer",
    MAP_P_BACK = "Retour",
    MAP_P_TAB = "Onglet",
    NAT_JUMP = "Sauter",
    NAT_INTERACT = "Interagir",
    NAT_BACK = "Retour",
    NAT_INSPECT = "Inspecter",
    NAT_TARGET_FRIEND = "Cibler les alliés",
    NAT_TARGET_ENEMY = "Cibler les ennemis",
    NAT_LAYER_LEFT = "Barre gauche",
    NAT_LAYER_RIGHT = "Barre droite",
    NAT_START = "Menu Start",
    NAT_SELECT = "Focus de l'interface",
    NAT_PING = "Ping",
    BINDING_MAP = "Mappage manette",
    PADDLE_KEY_REPLACES = "%s était lié à « %s » : la palette le remplace.",
    CAT_COMMON = "Raccourcis courants",
    DETECT_START = "Appuie maintenant sur chaque palette (L4, R4, L5, R5) : les touches reçues s'affichent pendant %d secondes.",
    DETECT_KEY = "Touche reçue : %s",
    DETECT_PAD = "Bouton manette reçu : %s",
    DETECT_END = "Détection des touches terminée.",
    QUEST_ITEM_TIP = "Objet de quête : ne pas vendre",
    QUEST_ITEM_FOR = "Objet de quête (%s) : ne pas vendre",
    QUEST_ITEM_SOLD = "Objet de quête vendu : %s. Rachetez-le dans l'onglet Rachat du marchand.",
    QUEST_ITEM_SOLD_SHORT = "Objet de quête vendu ! Voir l'onglet Rachat",
    NO_QUESTS = "Aucune quête en cours",
    QUESTS_TIP = "Quêtes : insérer un lien de quête",
    KEYBOARD_OFF = "Le clavier est désactivé (Options > AddOns > Easy Controller - Forever > Modules).",
    MOD_KEYBOARD = "Clavier (daisywheel / clavier 2 sticks)",
    MOD_QUEST_ITEMS = "Objets de quête : « ne pas vendre » dans les info-bulles, alerte chez le marchand",
    MOD_QUEST_LINKS = "Liens de quête dans le clavier (et liens par Maj+clic)",
}

LOCALES.deDE = {
    SHIFT = "Umschalt",
    SPACE = "Leertaste",
    BACKSPACE = "Löschen",
    SEND = "Senden",
    SEND_COMBAT = "Tastatur im Kampf geöffnet: zum Senden Enter drücken.",
    DRAG_HINT = "Ziehen, um die Tastatur zu verschieben (/ec lock zum Sperren)",
    LOCKED = "Position gesperrt: %s",
    TEXTURES_MISSING = "|cffff4040Texturen nicht gefunden|r: Spiel beenden und neu starten (/reload reicht für neue Dateien nicht).",
    COMBAT_UNAVAILABLE = "Im Kampf nicht möglich",
    HELP_PETAL = "Blatt",
    HELP_LETTER = "Buchstabe",
    HELP_CHANNEL = "Kanal",
    HELP_PICK = "Auswählen",
    HELP_CURSOR_L = "Cursor links",
    HELP_CURSOR_R = "Cursor rechts",
    HELP_TYPE_L = "Tippen links",
    HELP_TYPE_R = "Tippen rechts",
    OPT_INPUT = "Eingabe",
    OPT_METHOD = "Eingabemethode",
    METHOD_STICK = "Geteilte Tastatur",
    OPT_LAYOUT = "Layout (geteilte Tastatur)",
    OPT_DEADZONE = "Totzone des Sticks",
    OPT_MAGNET = "Magnetwirkung",
    OPT_CURVE = "Stick-Reaktion",
    CURVE_LINEAR = "Linear",
    CURVE_GENTLE = "Sanft (präzise in der Mitte)",
    CURVE_FAST = "Schnell",
    MAGNET_NONE = "Keine",
    MAGNET_WEAK = "Schwach",
    MAGNET_MEDIUM = "Mittel",
    MAGNET_STRONG = "Stark",
    OPT_LINE = "Cursorlinie anzeigen",
    MODE_SET = "Eingabemethode: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Sprache: %s",
    REPLY_TO = "Antwort an %s: ",
    WHISPER_NAME = "Flüstern an (Name, dann A): ",
    CHANNEL_NAMES = { "Sagen", "Schreien", "Gruppe", "Schlachtzug", "Gilde", "Allgemein (/1)", "Flüstern", "Antworten" },
    CHANNEL_UNAVAILABLE = "nicht verfügbar",
    BADGE_SHIFT = "UMSCH",
    BADGE_CAPS = "FESTSTELL",
    FONT_CHAT = "Chat-Schriftart",
    GLYPHS_NONE = "Keine Gamepad-Tastensymbole gefunden: die Symbole des Addons werden verwendet.",
    GLYPHS_FOUND = "%d Gamepad-Tastensymbole gefunden:",
    OPT_SUBTITLE = "Bildschirmtastatur, um mit dem Gamepad oder der Maus im Chat zu schreiben.",
    OPT_KEYBOARD = "Tastatur",
    OPT_LOCK = "Position sperren",
    OPT_AUTO = "Automatisch mit dem Chat öffnen",
    OPT_PAD_ONLY = "Nur wenn das Gamepad aktiv ist",
    OPT_INVERT = "Vertikale Stick-Achse umkehren",
    OPT_SCALE = "Tastaturgröße",
    SIZE_SMALL = "Klein",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Groß",
    SIZE_XL = "Sehr groß",
    OPT_ACTIONS = "Maustasten anzeigen (Umschalt, 123, Leertaste, Löschen, Senden, X)",
    OPT_STICKY = "Der gewählte Kanal wird zum Chatkanal (wie /p im Spiel)",
    OPT_LOOK = "Aussehen",
    OPT_FONT = "Schriftart",
    OPT_GLYPHS = "Tastensymbole",
    OPT_GAME_GLYPHS = "Tastensymbole des Spiels verwenden, falls verfügbar",
    OPT_PREDICTION = "Vorhersage",
    OPT_LANG = "Sprache der Vorschläge",
    OPT_LEARN = "Aus meinen Nachrichten lernen",
    OPT_RESET_POS = "Tastatur zurücksetzen",
    OPT_FORGET = "Gelernte Wörter vergessen",
    OPT_FORGET_CONFIRM = "Zum Bestätigen erneut klicken",
    LOADED = "v%s geladen. /ec für Hilfe.",
    WHEEL_NOTHING = "Ziel auf ein Feld",
    WHEEL_NOTHING_HINT = "In der Mitte schließt A, ohne etwas zu benutzen",
    WHEEL_LOCK = "Position sperren (entsperrt: das offene Rad mit der Maus ziehen)",
    WHEEL_MOVE = "Rad mit dem Steuerkreuz verschieben",
    WHEEL_RESET = "Zurück in die Bildschirmmitte",
    CFG_TAB_WHEEL = "Rad",
    WHEEL_NAME = "Verbrauchsgüter-Rad",
    WHEEL_ENABLE = "Verbrauchsgüter-Rad verwenden",
    WHEEL_INFO = "Gib ihm eine Taste: Reiter Gamepad, Liste Gegenstände (jede freie Taste oder jedes Paddle, in jeder Ebene) oder Esc > Tastenbelegung > AddOns.",
    WHEEL_INFO2 = "Offen: rechter Stick oder Steuerkreuz wählt, A benutzt, B schließt; die Maus klickt ein Feld. Funktioniert im Kampf (Essen und Trinken dort ausgegraut).",
    WHEEL_VARIANTS = "Jede getragene Variante nach der besten jeder Art (bis zu 12 Felder)",
    WHEEL_H_CATEGORIES = "Im Rad",
    WHEEL_CAT_FOOD = "Essen",
    WHEEL_CAT_DRINK = "Getränk",
    WHEEL_CAT_HEALTHPOTION = "Heiltränke",
    WHEEL_CAT_MANAPOTION = "Manatränke",
    WHEEL_CAT_HEALTHSTONE = "Gesundheitsstein",
    WHEEL_CAT_MANAGEM = "Manaedelstein",
    WHEEL_CAT_BANDAGE = "Verbände (auf dich)",
    WHEEL_CAT_BUFFFOOD = "Buff-Essen (satt)",
    WHEEL_CAT_ELIXIR = "Elixiere, Fläschchen und andere Tränke",
    WHEEL_CAT_SCROLL = "Rollen",
    WHEEL_AIM = "Wählen",
    WHEEL_USE = "Benutzen",
    WHEEL_CLOSE = "Schließen",
    CFG_TAB_SUPPLIES = "Vorräte",
    SUP_ENABLE = "Vorrats-Knöpfe anzeigen",
    SUP_INFO = "Ein runder Knopf pro Vorrat. Unter der unteren Schwelle leuchtet er, immer stärker bis zur kritischen (rot). Ein Klick öffnet die Taschen.",
    SUP_LOCK = "Position sperren (entsperrt: Knöpfe mit der Maus ziehen)",
    SUP_MOVE = "Mit dem Steuerkreuz verschieben",
    SUP_RESET = "Zurück an den Standardplatz",
    SUP_LAYOUT = "Richtung der Knöpfe",
    SUP_DIR_RIGHT = "Nach rechts",
    SUP_DIR_LEFT = "Nach links",
    SUP_DIR_DOWN = "Nach unten",
    SUP_DIR_UP = "Nach oben",
    SUP_SIZE = "Knopfgröße",
    SUP_H_TRACKED = "Verfolgte Vorräte",
    SUP_LOW = "Untere Schwelle",
    SUP_CRITICAL = "Kritische Schwelle",
    SUP_REMOVE = "Aus der Liste entfernen",
    SUP_H_ADD = "Einen Gegenstand aus den Taschen hinzufügen",
    SUP_ADD_SHOW = "Einen Gegenstand der Taschen zum Verfolgen wählen",
    SUP_ADD_HIDE = "Gegenstandsliste ausblenden",
    SUP_ADD_NONE = "Sonst nichts in deinen Taschen.",
    SUP_BAGS = "Freie Taschenplätze",
    SUP_AMMO = "Munition",
    SUP_TIP_COUNT = "Übrig: %d",
    SUP_TIP_THRESHOLDS = "Niedrig: %d, kritisch: %d",
    SUP_TIP_CLICK = "Klick: Taschen öffnen",
    CFG_TAB_VIBRATION = "Vibration",
    CFG_TEST = "Testen",
    CFG_P_TOGGLE = "Ein / aus",
    VIB_OFF = "Aus",
    CFG_P_PATTERN = "Muster / aus",
    VIB_ENABLE = "Controller vibrieren lassen",
    VIB_OFF_INFO = "Vibration aus: kein Ereignis lässt den Controller vibrieren.",
    VIB_INTENSITY = "Stärke (alle Vibrationen)",
    VIB_INFO = "Jedes Ereignis: Das Steuerkreuz wählt das Muster oder „Aus“, A testet es, X schaltet es ein oder aus.",
    VIB_UNAVAILABLE = "nicht verfügbar",
    VIB_UNAVAILABLE_TIP = "WoW Forever verbirgt Addons im Kampf deine genaue Gesundheit: Diese Vibration kann auf diesem Client nicht funktionieren.",
    VIB_H_COMBAT = "Kampf",
    VIB_H_SOCIAL = "Soziales",
    VIB_H_PROGRESS = "Fortschritt",
    VIB_H_ADDON = "Easy Controller",
    VIB_P_MICRO = "Mini-Tick",
    VIB_P_TICK = "Tick",
    VIB_P_DOUBLE = "Doppel-Tick",
    VIB_P_PULSE = "Impuls",
    VIB_P_LONG = "Lang",
    VIB_P_HEART = "Herzschlag",
    VIB_P_RISE = "Crescendo",
    VIB_E_LOWHEALTH = "Niedrige Gesundheit (unter 35 %, schneller unter 20 %)",
    VIB_E_BIGHIT = "Schwerer Treffer (über 10 % der Gesundheit)",
    VIB_E_DEATH = "Tod",
    VIB_E_INTERRUPTED = "Dein Zauber wird unterbrochen",
    VIB_E_LOSSOFCONTROL = "Kontrollverlust (Betäubung, Furcht, Stille…)",
    VIB_E_AGGRO = "Du ziehst Aggro",
    VIB_E_COMBAT = "Kampfbeginn",
    VIB_E_PROC = "Zauber-Proc (Hervorhebung)",
    VIB_E_ACTIONFAILED = "Aktion unmöglich (Reichweite, Mana, Ziel…)",
    VIB_E_WHISPER = "Flüstern erhalten",
    VIB_E_INVITE = "Gruppen- oder Schlachtzugseinladung",
    VIB_E_READYCHECK = "Bereitschaftscheck",
    VIB_E_REZSUMMON = "Wiederbelebung oder Beschwörung angeboten",
    VIB_E_TRADEDUEL = "Handels- oder Duellanfrage",
    VIB_E_LEVELUP = "Stufenaufstieg",
    VIB_E_QUEST = "Questziel oder Quest abgeschlossen",
    VIB_E_RARELOOT = "Seltene Beute oder besser",
    VIB_E_BAGSFULL = "Taschen voll (Spielmeldung)",
    VIB_E_DURABILITY = "Ausrüstung fast kaputt",
    VIB_E_LOWSTOCK = "Wenig Vorräte (Munition, Splitter…)",
    VIB_E_LOWSPACE = "Wenig Platz in den Taschen",
    VIB_E_WHEELTICK = "Rad: von Feld zu Feld",
    VIB_E_KEYPRESS = "Chat-Tastatur: Taste getippt",
    VIB_DIAG = "Vibrations-API: %s, Controller: %s, deine Gesundheit: %s, Vibration an: %s",
    VIB_DIAG_HIDDEN = "vom Spiel verborgen",
    VIB_DIAG_PATTERNS = "Muster: %s",
    OLD_FOLDER = "|cffff6060Der alte Ordner ControllerKeyboard ist noch installiert und wird ebenfalls geladen.|r Lösche Interface/AddOns/ControllerKeyboard (Spiel geschlossen): Easy Controller liegt jetzt in EasyController.",
    HELP = {
        "/ec - Tastatur öffnen",
        "/ec auto - automatisch mit dem Chat öffnen (aktuell: %s)",
        "/ec pad - nur automatisch öffnen, wenn das Gamepad aktiv ist (aktuell: %s)",
        "/ec learn - Wörter aus deinen Nachrichten lernen (aktuell: %s)",
        "/ec lock - Position sperren/entsperren (aktuell: %s)",
        "/ec mode wheel|stick - Daisywheel oder geteilte Tastatur",
        "/ec layout azerty|qwerty|qwertz|es|it - Layout der geteilten Tastatur",
        "/ec lang fr|en|de|es|it|both - Sprache der Vorschläge und Akzente",
        "/ec scale 0.8 - Tastaturgröße",
        "/ec invert - vertikale Stick-Achse umkehren",
        "/ec reset - Tastatur zurücksetzen",
        "/ec stats - Lernstatistik",
        "/ec forget - alle gelernten Wörter vergessen",
        "/ec glyphs - Gamepad-Tastensymbole des Spiels auflisten",
        "/ec config - Konfiguration (auch RB + Steuerkreuz unten)",
        "/ec map - Gamepad-Belegung (freie Tasten, Paddles)",
        "/ec keys - vom Spiel empfangene Tasten anzeigen (Paddles)",
        "/ec vibe [Muster] - die Controller-Vibration testen",
        "/ec debug - empfangene Tasten anzeigen",
        "Optionen: Esc > Optionen > AddOns > Easy Controller - Forever",
    },
    ON = "|cff40ff40an|r",
    OFF = "|cffff4040aus|r",
    STATS = "%d gelernte Wörter, %d Wörter im Wörterbuch.",
    FORGOT = "Gelernte Wörter gelöscht.",
    FORGET_CONFIRM = "Gib /ec forget confirm ein, um alle gelernten Wörter zu löschen.",
    NO_DICT = "Wörterbuch nicht verfügbar: %s",
    BINDING_TOGGLE = "Tastatur ein-/ausblenden",
    BADGE_HIDDEN = "Ausgeblendet",
    BADGE_RIGHT = "Rechts",
    BADGE_LEFT = "Links",
    BADGE_BOTTOM = "Unten",
    BADGE_TOP = "Oben",
    BADGE_OUTER = "Außenseite (links / rechts)",
    BADGE_OUTER_V = "Außenseite (oben / unten)",
    OPT_BADGE = "Name der zusätzlichen Tasten (R4...)",
    PLACE_MOVING = "wird verschoben",
    PLACE_P_CANCEL = "Abbrechen",
    PLACE_P_DROP = "Ablegen",
    PLACE_P_GRAB = "Aufnehmen",
    PLACE_P_SELECT = "Wählen",
    MAP_SLOT_HINT = "Feld der Gamepad-Leiste des Spiels: A, um einen Zauber, einen Gegenstand oder ein Makro hineinzulegen (wie im Editor des Spiels), X zum Leeren.",
    FEAT_RT_MODIFIER = "RT als Modifikator: Spielfunktionen auch auf RT + Paddles",
    FEAT_RT_MODIFIER_TIP = "Ohne: RT + ein Paddle nimmt Zauber, Gegenstände und Makros. Mit (Gamepad-Einstellung des Spiels „RT emuliert Alt“ oder Strg, so wie LT schon Umschalt sendet) wird RT + ein Paddle eine eigene Taste und nimmt auch Spielfunktionen. Die RT-Leiste des Spiels funktioniert weiter.",
    FEAT_QUEST_GLOW = "Oranger Rahmen um Questziel-Gegenstände in den Taschen (die das Spiel nicht markiert)",
    MAP_P_CONFIRM = "Bestätigen",
    PLACE_BAR = "Gamepad-Leiste",
    PLACE_P_PLACE = "Platz",
    FEAT_SHOW_STICKS = "L3 und R3 neben der Leiste anzeigen, mit ihrer Aktion (Autolauf, Ping...)",
    FEAT_SHORTCUT = "Gamepad-Kürzel zum Öffnen dieses Fensters",
    CFG_SHORTCUT_KEY = "Kombination: %s (A zum Ändern)",
    CFG_SHORTCUT_PRESS = "Halte eine Taste und drücke eine zweite... (Escape oder B allein: abbrechen)",
    CFG_SHORTCUT_RESET = "Zurück zu %s",
    CFG_TAB_GENERAL = "Allgemein",
    CFG_TAB_KEYBOARD = "Tastatur",
    CFG_TAB_GAMEPAD = "Gamepad",
    CFG_P_CHANGE = "Ändern",
    CFG_OPEN = "Konfiguration öffnen",
    CFG_OPEN_LATER = "Das Fenster von Easy Controller - Forever öffnet sich, sobald du wieder im Spiel bist (Optionen und Spielmenü geschlossen).",
    CFG_SETTINGS_HINT = "Alle Einstellungen sind im eigenen Fenster des Addons, per Gamepad oder Maus: RB + Steuerkreuz unten, /ec config oder seine Tastenbelegung.",
    CFG_H_FEATURES = "Funktionen",
    FEAT_DRAFTS = "Nachricht als Entwurf behalten, wenn das Spiel den Chat schließt",
    FEAT_LINKS = "Links per Umschalt+Klick und „Im Chat teilen“ zur Nachricht hinzufügen",
    FEAT_QUEST_TOOLTIP = "Orange Zeile „nicht verkaufen“ im Tooltip",
    FEAT_QUEST_SELL = "Warnung, wenn ein Questgegenstand verkauft wird",
    FEAT_QUEST_HOVER = "Warnung beim Auswählen eines Questgegenstands beim Händler (Gamepad-Taschen ohne Tooltips)",
    FEAT_EXTRA_DISPLAY = "Zusätzliche Tasten neben der Gamepad-Aktionsleiste anzeigen",
    MAP_IDENTIFY = "Hintere Paddles erkennen",
    MAP_IDENTIFY_HINT = "Drücke jedes hintere Paddle, wenn es verlangt wird, damit das Addon weiß, welche Taste es sendet (lege den Paddles zuerst in Steam Input Tastaturtasten fest).",
    MAP_PLACE = "Leiste und Tasten platzieren",
    MAP_PLACE_HINT = "Verschiebe die Gamepad-Leiste des Spiels schrittweise und platziere jede zusätzliche Taste (Paddles, L3, R3) direkt am Bildschirm darum herum.",
    MAP_WIZARD = "Drücke jetzt das Paddle %s.",
    MAP_WIZARD_DONE = "Hintere Paddles erkannt.",
    MAP_P_SKIP = "Überspringen",
    MAP_P_SECTION = "Abschnitt",
    MAP_P_LIST = "Liste",
    PLACE_TITLE = "Leiste und Tasten platzieren",
    PLACE_P_BUTTON = "Element",
    PLACE_P_SYM = "Spiegeln: %s",
    PLACE_P_RESET = "Standardplatz",
    PLACE_P_DONE = "Fertig",
    BINDING_CONFIG = "Easy Controller - Forever: Konfiguration",
    MOD_MAPPING = "Gamepad: zusätzliche Funktionen auf freien Tasten und hinteren Paddles",
    MAP_TITLE = "Gamepad-Belegung",
    MAP_ALONE = "Allein",
    MAP_FREE = "Frei",
    MAP_GAME = "Spiel",
    MAP_EMPTY_SLOT = "leer",
    MAP_BACK_ROW = "Hintere Paddles",
    MAP_LOCKED = "Hier keine Ebene: dieser Abzug ist in den Gamepad-Einstellungen des Spiels kein Modifikator, die Taste tut dasselbe wie ohne ihn.",
    MAP_SHARED_HINT = "Gleiche Taste wie ohne den Abzug (kein Modifikator): Zauber, Gegenstände und Makros. Für Spielfunktionen mache RT zum Modifikator (Reiter Allgemein).",
    MAP_SHARED_LOCKED = "Gleiche Taste wie %s, das eine Spielfunktion ausführt (%s): Eine Spielfunktion belegt die Taste in all ihren Ebenen. Lege stattdessen einen Zauber, einen Gegenstand oder ein Makro darauf, oder mache RT zum Modifikator (Reiter Allgemein).",
    MAP_SHARED_INACTIVE = "Nicht aktiv: Eine Spielfunktion braucht eine eigene Taste, und diese Ebene teilt die Taste des Paddles (der Abzug ist kein Modifikator). Mache RT zum Modifikator (Reiter Allgemein) oder wähle einen Zauber, einen Gegenstand oder ein Makro.",
    MAP_NATIVE_HINT = "Vom Spiel fest belegt, bleibt unverändert.",
    MAP_FREE_HINT = "Frei: A, um eine Funktion zuzuweisen.",
    MAP_ASSIGNED_HINT = "Von Easy Controller hinzugefügt (X zum Entfernen).",
    MAP_PADDLE_KEY = "Paddle-Taste: %s (Y zum erneuten Erlernen)",
    MAP_PADDLE_PRESS = "Drücke jetzt das Paddle... (B zum Abbrechen)",
    MAP_NOTHING = "Nichts hier",
    MAP_TAB_GAME = "Spiel",
    MAP_TAB_SPELLS = "Zauber",
    MAP_TAB_ITEMS = "Items",
    MAP_TAB_MACROS = "Makros",
    MAP_TAB_BAR = "Leiste",
    MAP_P_MOVE = "Bewegen",
    MAP_P_CHOOSE = "Wählen",
    MAP_P_CLEAR = "Entfernen",
    MAP_P_KEY = "Paddle-Taste",
    MAP_P_LAYER = "Ebene",
    MAP_P_CLOSE = "Schließen",
    MAP_P_BACK = "Zurück",
    MAP_P_TAB = "Reiter",
    NAT_JUMP = "Springen",
    NAT_INTERACT = "Interagieren",
    NAT_BACK = "Zurück",
    NAT_INSPECT = "Betrachten",
    NAT_TARGET_FRIEND = "Verbündete anvisieren",
    NAT_TARGET_ENEMY = "Feinde anvisieren",
    NAT_LAYER_LEFT = "Linke Leiste",
    NAT_LAYER_RIGHT = "Rechte Leiste",
    NAT_START = "Startmenü",
    NAT_SELECT = "Interface-Fokus",
    NAT_PING = "Ping",
    BINDING_MAP = "Gamepad-Belegung",
    PADDLE_KEY_REPLACES = "%s war mit „%s“ belegt: das Paddle übernimmt die Taste.",
    CAT_COMMON = "Häufige Tastenbelegungen",
    DETECT_START = "Drücke jetzt jedes hintere Paddle (L4, R4, L5, R5): die empfangenen Tasten werden %d Sekunden lang angezeigt.",
    DETECT_KEY = "Taste empfangen: %s",
    DETECT_PAD = "Gamepad-Taste empfangen: %s",
    DETECT_END = "Tastenerkennung beendet.",
    QUEST_ITEM_TIP = "Questgegenstand: nicht verkaufen",
    QUEST_ITEM_FOR = "Questgegenstand (%s): nicht verkaufen",
    QUEST_ITEM_SOLD = "Questgegenstand verkauft: %s. Kaufe ihn im Rückkauf-Reiter des Händlers zurück.",
    QUEST_ITEM_SOLD_SHORT = "Questgegenstand verkauft! Siehe Rückkauf",
    NO_QUESTS = "Keine laufende Quest",
    QUESTS_TIP = "Quests: Questlink einfügen",
    KEYBOARD_OFF = "Die Tastatur ist ausgeschaltet (Optionen > AddOns > Easy Controller - Forever > Module).",
    MOD_KEYBOARD = "Tastatur (Daisywheel / geteilte Tastatur)",
    MOD_QUEST_ITEMS = "Questgegenstände: „nicht verkaufen“ im Tooltip, Warnung beim Händler",
    MOD_QUEST_LINKS = "Questlinks in der Tastatur (und Links per Umschalt+Klick)",
}

LOCALES.esES = {
    SHIFT = "Mayús",
    SPACE = "Espacio",
    BACKSPACE = "Borrar",
    SEND = "Enviar",
    SEND_COMBAT = "Teclado abierto en combate: pulsa Intro para enviar.",
    DRAG_HINT = "Arrastra para mover el teclado (/ec lock para bloquearlo)",
    LOCKED = "Posición bloqueada: %s",
    TEXTURES_MISSING = "|cffff4040Texturas no encontradas|r: cierra y reinicia el juego (/reload no basta para archivos nuevos).",
    COMBAT_UNAVAILABLE = "No es posible en combate",
    HELP_PETAL = "Pétalo",
    HELP_LETTER = "Letra",
    HELP_CHANNEL = "Canal",
    HELP_PICK = "Elegir",
    HELP_CURSOR_L = "Cursor izq.",
    HELP_CURSOR_R = "Cursor der.",
    HELP_TYPE_L = "Escribir izq.",
    HELP_TYPE_R = "Escribir der.",
    OPT_INPUT = "Escritura",
    OPT_METHOD = "Método de escritura",
    METHOD_STICK = "Teclado dividido",
    OPT_LAYOUT = "Distribución (teclado dividido)",
    OPT_DEADZONE = "Zona muerta del stick",
    OPT_MAGNET = "Efecto imán",
    OPT_CURVE = "Respuesta del stick",
    CURVE_LINEAR = "Lineal",
    CURVE_GENTLE = "Suave (precisa en el centro)",
    CURVE_FAST = "Rápida",
    MAGNET_NONE = "Ninguno",
    MAGNET_WEAK = "Débil",
    MAGNET_MEDIUM = "Medio",
    MAGNET_STRONG = "Fuerte",
    OPT_LINE = "Mostrar la línea del cursor",
    MODE_SET = "Método de escritura: %s",
    LAYOUT_SET = "Distribución: %s",
    LANG_SET = "Idioma: %s",
    REPLY_TO = "Responder a %s: ",
    WHISPER_NAME = "Susurrar a (nombre, luego A): ",
    CHANNEL_NAMES = { "Decir", "Gritar", "Grupo", "Banda", "Hermandad", "General (/1)", "Susurrar", "Responder" },
    CHANNEL_UNAVAILABLE = "no disponible",
    BADGE_SHIFT = "MAYÚS",
    BADGE_CAPS = "BLOQ MAYÚS",
    FONT_CHAT = "Fuente del chat",
    GLYPHS_NONE = "No se encontraron iconos de botones del mando: se usan los del addon.",
    GLYPHS_FOUND = "%d iconos de botones del mando encontrados:",
    OPT_SUBTITLE = "Teclado en pantalla para escribir en el chat con el mando o el ratón.",
    OPT_KEYBOARD = "Teclado",
    OPT_LOCK = "Bloquear la posición",
    OPT_AUTO = "Abrir automáticamente con el chat",
    OPT_PAD_ONLY = "Solo cuando el mando está activo",
    OPT_INVERT = "Invertir el eje vertical de los sticks",
    OPT_SCALE = "Tamaño del teclado",
    SIZE_SMALL = "Pequeño",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Muy grande",
    OPT_ACTIONS = "Mostrar los botones del ratón (Mayús, 123, Espacio, Borrar, Enviar, X)",
    OPT_STICKY = "El canal elegido pasa a ser el del chat (como escribir /p en el juego)",
    OPT_LOOK = "Apariencia",
    OPT_FONT = "Fuente",
    OPT_GLYPHS = "Iconos de botones",
    OPT_GAME_GLYPHS = "Usar los iconos de botones del juego si están disponibles",
    OPT_PREDICTION = "Predicción",
    OPT_LANG = "Idioma de las sugerencias",
    OPT_LEARN = "Aprender de mis mensajes",
    OPT_RESET_POS = "Recolocar el teclado",
    OPT_FORGET = "Olvidar las palabras aprendidas",
    OPT_FORGET_CONFIRM = "Pulsa otra vez para confirmar",
    LOADED = "v%s cargado. /ec para la ayuda.",
    WHEEL_NOTHING = "Apunta a una casilla",
    WHEEL_NOTHING_HINT = "En el centro, A cierra sin usar nada",
    WHEEL_LOCK = "Bloquear la posición (desbloqueada: arrastrar la rueda abierta con el ratón)",
    WHEEL_MOVE = "Mover la rueda con la cruceta",
    WHEEL_RESET = "Volver al centro de la pantalla",
    CFG_TAB_WHEEL = "Rueda",
    WHEEL_NAME = "Rueda de consumibles",
    WHEEL_ENABLE = "Usar la rueda de consumibles",
    WHEEL_INFO = "Dale una tecla: pestaña Mando, lista Objetos (cualquier botón libre o paleta, en cualquier capa), o Esc > Asignación de teclas > AddOns.",
    WHEEL_INFO2 = "Abierta: el stick derecho o la cruceta elige, A usa, B cierra; el ratón hace clic en una casilla. Funciona en combate (comida y bebida en gris).",
    WHEEL_VARIANTS = "Todas las variantes que llevas, tras la mejor de cada tipo (hasta 12 casillas)",
    WHEEL_H_CATEGORIES = "En la rueda",
    WHEEL_CAT_FOOD = "Comida",
    WHEEL_CAT_DRINK = "Bebida",
    WHEEL_CAT_HEALTHPOTION = "Pociones de sanación",
    WHEEL_CAT_MANAPOTION = "Pociones de maná",
    WHEEL_CAT_HEALTHSTONE = "Piedra de salud",
    WHEEL_CAT_MANAGEM = "Gema de maná",
    WHEEL_CAT_BANDAGE = "Vendas (sobre ti)",
    WHEEL_CAT_BUFFFOOD = "Comida de bonificación (bien alimentado)",
    WHEEL_CAT_ELIXIR = "Elixires, frascos y otras pociones",
    WHEEL_CAT_SCROLL = "Pergaminos",
    WHEEL_AIM = "Elegir",
    WHEEL_USE = "Usar",
    WHEEL_CLOSE = "Cerrar",
    CFG_TAB_SUPPLIES = "Reservas",
    SUP_ENABLE = "Mostrar los botones de reservas",
    SUP_INFO = "Un botón redondo por recurso. Por debajo de su umbral bajo brilla, cada vez más hasta el crítico (rojo). Un clic abre las bolsas.",
    SUP_LOCK = "Bloquear la posición (desbloqueada: arrastrar los botones con el ratón)",
    SUP_MOVE = "Mover con la cruceta",
    SUP_RESET = "Volver al lugar por defecto",
    SUP_LAYOUT = "Dirección de los botones",
    SUP_DIR_RIGHT = "Hacia la derecha",
    SUP_DIR_LEFT = "Hacia la izquierda",
    SUP_DIR_DOWN = "Hacia abajo",
    SUP_DIR_UP = "Hacia arriba",
    SUP_SIZE = "Tamaño de los botones",
    SUP_H_TRACKED = "Recursos seguidos",
    SUP_LOW = "Umbral bajo",
    SUP_CRITICAL = "Umbral crítico",
    SUP_REMOVE = "Quitar de la lista",
    SUP_H_ADD = "Añadir un objeto de tus bolsas",
    SUP_ADD_SHOW = "Elegir un objeto de tus bolsas para seguir",
    SUP_ADD_HIDE = "Ocultar la lista de objetos",
    SUP_ADD_NONE = "Nada más en tus bolsas.",
    SUP_BAGS = "Huecos libres en las bolsas",
    SUP_AMMO = "Munición",
    SUP_TIP_COUNT = "Quedan: %d",
    SUP_TIP_THRESHOLDS = "Bajo: %d, crítico: %d",
    SUP_TIP_CLICK = "Clic: abrir las bolsas",
    CFG_TAB_VIBRATION = "Vibración",
    CFG_TEST = "Probar",
    CFG_P_TOGGLE = "Activar / desactivar",
    VIB_OFF = "Desactivado",
    CFG_P_PATTERN = "Patrón / desactivado",
    VIB_ENABLE = "Hacer vibrar el mando",
    VIB_OFF_INFO = "Vibraciones desactivadas: ningún evento hace vibrar el mando.",
    VIB_INTENSITY = "Intensidad (todas las vibraciones)",
    VIB_INFO = "Cada evento: la cruceta elige su patrón o «Desactivado», A lo prueba, X lo activa o desactiva.",
    VIB_UNAVAILABLE = "no disponible",
    VIB_UNAVAILABLE_TIP = "WoW Forever oculta a los addons tu salud exacta en combate: esta vibración no puede funcionar en este cliente.",
    VIB_H_COMBAT = "Combate",
    VIB_H_SOCIAL = "Social",
    VIB_H_PROGRESS = "Progreso",
    VIB_H_ADDON = "Easy Controller",
    VIB_P_MICRO = "Microtic",
    VIB_P_TICK = "Tic",
    VIB_P_DOUBLE = "Doble tic",
    VIB_P_PULSE = "Impulso",
    VIB_P_LONG = "Larga",
    VIB_P_HEART = "Latido",
    VIB_P_RISE = "Crescendo",
    VIB_E_LOWHEALTH = "Salud baja (por debajo del 35 %, más rápido por debajo del 20 %)",
    VIB_E_BIGHIT = "Golpe fuerte recibido (más del 10 % de la salud)",
    VIB_E_DEATH = "Muerte",
    VIB_E_INTERRUPTED = "Tu hechizo es interrumpido",
    VIB_E_LOSSOFCONTROL = "Pérdida de control (aturdimiento, miedo, silencio…)",
    VIB_E_AGGRO = "Atraes la amenaza",
    VIB_E_COMBAT = "Entrada en combate",
    VIB_E_PROC = "Activación de hechizo (resaltado)",
    VIB_E_ACTIONFAILED = "Acción imposible (alcance, maná, objetivo…)",
    VIB_E_WHISPER = "Susurro recibido",
    VIB_E_INVITE = "Invitación a grupo o banda",
    VIB_E_READYCHECK = "Comprobación de disponibilidad",
    VIB_E_REZSUMMON = "Resurrección o invocación ofrecida",
    VIB_E_TRADEDUEL = "Solicitud de comercio o duelo",
    VIB_E_LEVELUP = "Subida de nivel",
    VIB_E_QUEST = "Objetivo o misión completados",
    VIB_E_RARELOOT = "Botín raro o mejor",
    VIB_E_BAGSFULL = "Bolsas llenas (mensaje del juego)",
    VIB_E_DURABILITY = "Equipo casi roto",
    VIB_E_LOWSTOCK = "Reservas bajas (munición, fragmentos…)",
    VIB_E_LOWSPACE = "Poco espacio en las bolsas",
    VIB_E_WHEELTICK = "Rueda: paso de una casilla a otra",
    VIB_E_KEYPRESS = "Teclado del chat: tecla pulsada",
    VIB_DIAG = "API de vibración: %s, mando: %s, tu salud: %s, vibraciones activadas: %s",
    VIB_DIAG_HIDDEN = "oculta por el juego",
    VIB_DIAG_PATTERNS = "Patrones: %s",
    OLD_FOLDER = "|cffff6060La antigua carpeta ControllerKeyboard sigue instalada y también se carga.|r Borra Interface/AddOns/ControllerKeyboard (con el juego cerrado): Easy Controller está ahora en EasyController.",
    HELP = {
        "/ec - abrir el teclado",
        "/ec auto - abrir automáticamente con el chat (actual: %s)",
        "/ec pad - abrir automáticamente solo si el mando está activo (actual: %s)",
        "/ec learn - aprender las palabras de tus mensajes (actual: %s)",
        "/ec lock - bloquear/desbloquear la posición (actual: %s)",
        "/ec mode wheel|stick - daisywheel o teclado dividido",
        "/ec layout azerty|qwerty|qwertz|es|it - distribución del teclado dividido",
        "/ec lang fr|en|de|es|it|both - idioma de las sugerencias y de los acentos",
        "/ec scale 0.8 - tamaño del teclado",
        "/ec invert - invertir el eje vertical del stick",
        "/ec reset - recolocar el teclado",
        "/ec stats - estadísticas de aprendizaje",
        "/ec forget - olvidar todas las palabras aprendidas",
        "/ec glyphs - listar los iconos de botones del mando del juego",
        "/ec config - configuración (también RB + cruceta abajo)",
        "/ec map - asignación del mando (botones libres, paletas)",
        "/ec keys - mostrar las teclas que recibe el juego (paletas)",
        "/ec vibe [patrón] - probar la vibración del mando",
        "/ec debug - mostrar los botones recibidos",
        "Opciones: Esc > Opciones > AddOns > Easy Controller - Forever",
    },
    ON = "|cff40ff40sí|r",
    OFF = "|cffff4040no|r",
    STATS = "%d palabras aprendidas, %d palabras en el diccionario.",
    FORGOT = "Palabras aprendidas borradas.",
    FORGET_CONFIRM = "Escribe /ec forget confirm para borrar todas las palabras aprendidas.",
    NO_DICT = "Diccionario no disponible: %s",
    BINDING_TOGGLE = "Mostrar/ocultar el teclado",
    BADGE_HIDDEN = "Oculto",
    BADGE_RIGHT = "A la derecha",
    BADGE_LEFT = "A la izquierda",
    BADGE_BOTTOM = "Abajo",
    BADGE_TOP = "Arriba",
    BADGE_OUTER = "Lado exterior (izquierda / derecha)",
    BADGE_OUTER_V = "Lado exterior (arriba / abajo)",
    OPT_BADGE = "Nombre de los botones extra (R4...)",
    PLACE_MOVING = "moviéndose",
    PLACE_P_CANCEL = "Cancelar",
    PLACE_P_DROP = "Soltar",
    PLACE_P_GRAB = "Coger",
    PLACE_P_SELECT = "Elegir",
    MAP_SLOT_HINT = "Casilla de la barra del mando del juego: A para poner un hechizo, un objeto o una macro (como el editor del juego), X para vaciarla.",
    FEAT_RT_MODIFIER = "RT actúa como modificador: funciones del juego también en RT + paletas",
    FEAT_RT_MODIFIER_TIP = "Sin él, RT + una paleta admite hechizos, objetos y macros. Con él (el ajuste del mando del juego «RT emula Alt», o Ctrl, como LT ya envía Mayús), RT + una paleta es una tecla propia y admite también funciones del juego. La barra RT del juego sigue funcionando.",
    FEAT_QUEST_GLOW = "Borde naranja en los objetos que pide una misión en las bolsas (los que el juego no marca)",
    MAP_P_CONFIRM = "Confirmar",
    PLACE_BAR = "Barra del mando",
    PLACE_P_PLACE = "Sitio",
    FEAT_SHOW_STICKS = "Mostrar L3 y R3 junto a la barra, con su acción (correr automático, ping...)",
    FEAT_SHORTCUT = "Atajo del mando para abrir este panel",
    CFG_SHORTCUT_KEY = "Combinación: %s (A para cambiarla)",
    CFG_SHORTCUT_PRESS = "Mantén un botón y pulsa un segundo... (Escape o B solo: cancelar)",
    CFG_SHORTCUT_RESET = "Volver a %s",
    CFG_TAB_GENERAL = "General",
    CFG_TAB_KEYBOARD = "Teclado",
    CFG_TAB_GAMEPAD = "Mando",
    CFG_P_CHANGE = "Cambiar",
    CFG_OPEN = "Abrir la configuración",
    CFG_OPEN_LATER = "El panel de Easy Controller - Forever se abrirá cuando vuelvas al juego (opciones y menú del juego cerrados).",
    CFG_SETTINGS_HINT = "Todos los ajustes están en el panel del addon, con el mando o el ratón: RB + cruceta abajo, /ec config o su atajo.",
    CFG_H_FEATURES = "Funciones",
    FEAT_DRAFTS = "Guardar el mensaje como borrador cuando el juego cierra el chat",
    FEAT_LINKS = "Añadir al mensaje los enlaces de Mayús+clic y «Compartir en el chat»",
    FEAT_QUEST_TOOLTIP = "Línea naranja «no vender» en las descripciones",
    FEAT_QUEST_SELL = "Aviso al vender un objeto de misión",
    FEAT_QUEST_HOVER = "Aviso al seleccionar un objeto de misión en un vendedor (bolsas del mando sin descripciones)",
    FEAT_EXTRA_DISPLAY = "Mostrar los botones extra junto a la barra de acción del mando",
    MAP_IDENTIFY = "Identificar las paletas traseras",
    MAP_IDENTIFY_HINT = "Pulsa cada paleta trasera cuando se te pida, para que el addon sepa qué tecla o botón envía (asigna antes teclas del teclado a las paletas en Steam Input).",
    MAP_PLACE = "Colocar la barra y los botones",
    MAP_PLACE_HINT = "Mueve la barra del mando del juego por pasos y coloca cada botón extra (paletas, L3, R3) a su alrededor, directamente en la pantalla.",
    MAP_WIZARD = "Pulsa ahora la paleta %s.",
    MAP_WIZARD_DONE = "Paletas traseras identificadas.",
    MAP_P_SKIP = "Saltar",
    MAP_P_SECTION = "Sección",
    MAP_P_LIST = "Lista",
    PLACE_TITLE = "Colocar la barra y los botones",
    PLACE_P_BUTTON = "Elemento",
    PLACE_P_SYM = "Simetría: %s",
    PLACE_P_RESET = "Sitio por defecto",
    PLACE_P_DONE = "Terminar",
    BINDING_CONFIG = "Configuración de Easy Controller - Forever",
    MOD_MAPPING = "Mando: funciones extra en los botones libres y las paletas traseras",
    MAP_TITLE = "Asignación del mando",
    MAP_ALONE = "Solo",
    MAP_FREE = "Libre",
    MAP_GAME = "Juego",
    MAP_EMPTY_SLOT = "vacío",
    MAP_BACK_ROW = "Paletas traseras",
    MAP_LOCKED = "Aquí no hay capa: este gatillo no es un modificador en los ajustes del mando del juego, el botón hace lo mismo que sin él.",
    MAP_SHARED_HINT = "Misma tecla que sin el gatillo (no es modificador): hechizos, objetos y macros. Para funciones del juego, haz de RT un modificador (pestaña General).",
    MAP_SHARED_LOCKED = "Misma tecla que %s, que ejecuta una función del juego (%s): una función del juego ocupa la tecla en todas sus capas. Pon ahí un hechizo, un objeto o una macro, o haz de RT un modificador (pestaña General).",
    MAP_SHARED_INACTIVE = "Inactiva: una función del juego necesita una tecla propia, y esta capa comparte la tecla de la paleta (el gatillo no es modificador). Haz de RT un modificador (pestaña General), o elige un hechizo, un objeto o una macro.",
    MAP_NATIVE_HINT = "Función fija del juego, se queda como está.",
    MAP_FREE_HINT = "Libre: A para darle una función.",
    MAP_ASSIGNED_HINT = "Añadido por Easy Controller (X para quitar).",
    MAP_PADDLE_KEY = "Tecla de la paleta: %s (Y para aprenderla de nuevo)",
    MAP_PADDLE_PRESS = "Pulsa ahora la paleta... (B para cancelar)",
    MAP_NOTHING = "Nada aquí",
    MAP_TAB_GAME = "Juego",
    MAP_TAB_SPELLS = "Hechizos",
    MAP_TAB_ITEMS = "Objetos",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Barra",
    MAP_P_MOVE = "Mover",
    MAP_P_CHOOSE = "Elegir",
    MAP_P_CLEAR = "Quitar",
    MAP_P_KEY = "Tecla de paleta",
    MAP_P_LAYER = "Capa",
    MAP_P_CLOSE = "Cerrar",
    MAP_P_BACK = "Volver",
    MAP_P_TAB = "Pestaña",
    NAT_JUMP = "Saltar",
    NAT_INTERACT = "Interactuar",
    NAT_BACK = "Volver",
    NAT_INSPECT = "Inspeccionar",
    NAT_TARGET_FRIEND = "Seleccionar aliados",
    NAT_TARGET_ENEMY = "Seleccionar enemigos",
    NAT_LAYER_LEFT = "Barra izquierda",
    NAT_LAYER_RIGHT = "Barra derecha",
    NAT_START = "Menú Start",
    NAT_SELECT = "Foco de la interfaz",
    NAT_PING = "Ping",
    BINDING_MAP = "Asignación del mando",
    PADDLE_KEY_REPLACES = "%s estaba asignada a «%s»: la paleta la sustituye.",
    CAT_COMMON = "Atajos habituales",
    DETECT_START = "Pulsa ahora cada paleta trasera (L4, R4, L5, R5): las teclas recibidas se muestran durante %d segundos.",
    DETECT_KEY = "Tecla recibida: %s",
    DETECT_PAD = "Botón del mando recibido: %s",
    DETECT_END = "Detección de teclas terminada.",
    QUEST_ITEM_TIP = "Objeto de misión: no vender",
    QUEST_ITEM_FOR = "Objeto de misión (%s): no vender",
    QUEST_ITEM_SOLD = "Objeto de misión vendido: %s. Recómpralo en la pestaña Recomprar del vendedor.",
    QUEST_ITEM_SOLD_SHORT = "¡Objeto de misión vendido! Mira la pestaña Recomprar",
    NO_QUESTS = "Ninguna misión en curso",
    QUESTS_TIP = "Misiones: insertar un enlace de misión",
    KEYBOARD_OFF = "El teclado está desactivado (Opciones > AddOns > Easy Controller - Forever > Módulos).",
    MOD_KEYBOARD = "Teclado (daisywheel / teclado dividido)",
    MOD_QUEST_ITEMS = "Objetos de misión: «no vender» en las descripciones, aviso en el vendedor",
    MOD_QUEST_LINKS = "Enlaces de misión en el teclado (y enlaces con Mayús+clic)",
}
LOCALES.esMX = LOCALES.esES

LOCALES.itIT = {
    SHIFT = "Maiusc",
    SPACE = "Spazio",
    BACKSPACE = "Cancella",
    SEND = "Invia",
    SEND_COMBAT = "Tastiera aperta in combattimento: premi Invio per inviare.",
    DRAG_HINT = "Trascina per spostare la tastiera (/ec lock per bloccarla)",
    LOCKED = "Posizione bloccata: %s",
    TEXTURES_MISSING = "|cffff4040Texture non trovate|r: chiudi e riavvia il gioco (/reload non basta per i nuovi file).",
    COMBAT_UNAVAILABLE = "Impossibile in combattimento",
    HELP_PETAL = "Petalo",
    HELP_LETTER = "Lettera",
    HELP_CHANNEL = "Canale",
    HELP_PICK = "Scegli",
    HELP_CURSOR_L = "Cursore sx",
    HELP_CURSOR_R = "Cursore dx",
    HELP_TYPE_L = "Scrivi sx",
    HELP_TYPE_R = "Scrivi dx",
    OPT_INPUT = "Scrittura",
    OPT_METHOD = "Metodo di scrittura",
    METHOD_STICK = "Tastiera divisa",
    OPT_LAYOUT = "Layout (tastiera divisa)",
    OPT_DEADZONE = "Zona morta dello stick",
    OPT_MAGNET = "Effetto calamita",
    OPT_CURVE = "Risposta dello stick",
    CURVE_LINEAR = "Lineare",
    CURVE_GENTLE = "Morbida (precisa al centro)",
    CURVE_FAST = "Rapida",
    MAGNET_NONE = "Nessuno",
    MAGNET_WEAK = "Debole",
    MAGNET_MEDIUM = "Medio",
    MAGNET_STRONG = "Forte",
    OPT_LINE = "Mostra la linea del cursore",
    MODE_SET = "Metodo di scrittura: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Lingua: %s",
    REPLY_TO = "Rispondi a %s: ",
    WHISPER_NAME = "Sussurra a (nome, poi A): ",
    CHANNEL_NAMES = { "Parla", "Urla", "Gruppo", "Incursione", "Gilda", "Generale (/1)", "Sussurra", "Rispondi" },
    CHANNEL_UNAVAILABLE = "non disponibile",
    BADGE_SHIFT = "MAIUSC",
    BADGE_CAPS = "BLOC MAIUSC",
    FONT_CHAT = "Carattere della chat",
    GLYPHS_NONE = "Nessuna icona dei pulsanti del controller trovata: vengono usate quelle dell'addon.",
    GLYPHS_FOUND = "%d icone dei pulsanti del controller trovate:",
    OPT_SUBTITLE = "Tastiera su schermo per scrivere in chat con il controller o il mouse.",
    OPT_KEYBOARD = "Tastiera",
    OPT_LOCK = "Blocca la posizione",
    OPT_AUTO = "Apri automaticamente con la chat",
    OPT_PAD_ONLY = "Solo quando il controller è attivo",
    OPT_INVERT = "Inverti l'asse verticale degli stick",
    OPT_SCALE = "Dimensione della tastiera",
    SIZE_SMALL = "Piccola",
    SIZE_NORMAL = "Normale",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Molto grande",
    OPT_ACTIONS = "Mostra i pulsanti del mouse (Maiusc, 123, Spazio, Cancella, Invia, X)",
    OPT_STICKY = "Il canale scelto diventa quello della chat (come scrivere /p nel gioco)",
    OPT_LOOK = "Aspetto",
    OPT_FONT = "Carattere",
    OPT_GLYPHS = "Icone dei pulsanti",
    OPT_GAME_GLYPHS = "Usa le icone dei pulsanti del gioco se disponibili",
    OPT_PREDICTION = "Previsione",
    OPT_LANG = "Lingua dei suggerimenti",
    OPT_LEARN = "Impara dai miei messaggi",
    OPT_RESET_POS = "Riposiziona la tastiera",
    OPT_FORGET = "Dimentica le parole apprese",
    OPT_FORGET_CONFIRM = "Clicca di nuovo per confermare",
    LOADED = "v%s caricato. /ec per l'aiuto.",
    WHEEL_NOTHING = "Punta una casella",
    WHEEL_NOTHING_HINT = "Al centro, A chiude senza usare nulla",
    WHEEL_LOCK = "Blocca la posizione (sbloccata: trascina la ruota aperta con il mouse)",
    WHEEL_MOVE = "Sposta la ruota con la croce",
    WHEEL_RESET = "Torna al centro dello schermo",
    CFG_TAB_WHEEL = "Ruota",
    WHEEL_NAME = "Ruota dei consumabili",
    WHEEL_ENABLE = "Usa la ruota dei consumabili",
    WHEEL_INFO = "Assegnale un tasto: scheda Controller, lista Oggetti (qualsiasi pulsante libero o levetta, in ogni livello), o Esc > Assegnazione tasti > AddOns.",
    WHEEL_INFO2 = "Aperta: lo stick destro o la croce sceglie, A usa, B chiude; il mouse clicca una casella. Funziona in combattimento (cibo e bevande in grigio).",
    WHEEL_VARIANTS = "Tutte le varianti portate, dopo la migliore di ogni tipo (fino a 12 caselle)",
    WHEEL_H_CATEGORIES = "Nella ruota",
    WHEEL_CAT_FOOD = "Cibo",
    WHEEL_CAT_DRINK = "Bevanda",
    WHEEL_CAT_HEALTHPOTION = "Pozioni curative",
    WHEEL_CAT_MANAPOTION = "Pozioni di mana",
    WHEEL_CAT_HEALTHSTONE = "Pietra della salute",
    WHEEL_CAT_MANAGEM = "Gemma del mana",
    WHEEL_CAT_BANDAGE = "Bende (su di te)",
    WHEEL_CAT_BUFFFOOD = "Cibo con bonus (ben nutrito)",
    WHEEL_CAT_ELIXIR = "Elisir, tonici e altre pozioni",
    WHEEL_CAT_SCROLL = "Pergamene",
    WHEEL_AIM = "Scegli",
    WHEEL_USE = "Usa",
    WHEEL_CLOSE = "Chiudi",
    CFG_TAB_SUPPLIES = "Scorte",
    SUP_ENABLE = "Mostra i pulsanti delle scorte",
    SUP_INFO = "Un pulsante rotondo per risorsa. Sotto la soglia bassa si illumina, sempre di più fino a quella critica (rossa). Un clic apre le borse.",
    SUP_LOCK = "Blocca la posizione (sbloccata: trascina i pulsanti con il mouse)",
    SUP_MOVE = "Sposta con la croce",
    SUP_RESET = "Torna al posto predefinito",
    SUP_LAYOUT = "Direzione dei pulsanti",
    SUP_DIR_RIGHT = "Verso destra",
    SUP_DIR_LEFT = "Verso sinistra",
    SUP_DIR_DOWN = "Verso il basso",
    SUP_DIR_UP = "Verso l'alto",
    SUP_SIZE = "Dimensione dei pulsanti",
    SUP_H_TRACKED = "Risorse seguite",
    SUP_LOW = "Soglia bassa",
    SUP_CRITICAL = "Soglia critica",
    SUP_REMOVE = "Togli dalla lista",
    SUP_H_ADD = "Aggiungi un oggetto dalle borse",
    SUP_ADD_SHOW = "Scegli un oggetto delle borse da seguire",
    SUP_ADD_HIDE = "Nascondi la lista degli oggetti",
    SUP_ADD_NONE = "Nient'altro nelle borse.",
    SUP_BAGS = "Posti liberi nelle borse",
    SUP_AMMO = "Munizioni",
    SUP_TIP_COUNT = "Rimasti: %d",
    SUP_TIP_THRESHOLDS = "Basso: %d, critico: %d",
    SUP_TIP_CLICK = "Clic: apri le borse",
    CFG_TAB_VIBRATION = "Vibrazione",
    CFG_TEST = "Prova",
    CFG_P_TOGGLE = "Attiva / disattiva",
    VIB_OFF = "Disattivato",
    CFG_P_PATTERN = "Schema / disattivato",
    VIB_ENABLE = "Far vibrare il controller",
    VIB_OFF_INFO = "Vibrazioni disattivate: nessun evento fa vibrare il controller.",
    VIB_INTENSITY = "Intensità (tutte le vibrazioni)",
    VIB_INFO = "Ogni evento: la croce sceglie lo schema o «Disattivato», A lo prova, X lo attiva o disattiva.",
    VIB_UNAVAILABLE = "non disponibile",
    VIB_UNAVAILABLE_TIP = "WoW Forever nasconde agli addon la tua salute esatta in combattimento: questa vibrazione non può funzionare su questo client.",
    VIB_H_COMBAT = "Combattimento",
    VIB_H_SOCIAL = "Social",
    VIB_H_PROGRESS = "Progressi",
    VIB_H_ADDON = "Easy Controller",
    VIB_P_MICRO = "Micro-tic",
    VIB_P_TICK = "Tic",
    VIB_P_DOUBLE = "Doppio tic",
    VIB_P_PULSE = "Impulso",
    VIB_P_LONG = "Lunga",
    VIB_P_HEART = "Battito",
    VIB_P_RISE = "Crescendo",
    VIB_E_LOWHEALTH = "Salute bassa (sotto il 35 %, più rapido sotto il 20 %)",
    VIB_E_BIGHIT = "Colpo pesante subito (oltre il 10 % della salute)",
    VIB_E_DEATH = "Morte",
    VIB_E_INTERRUPTED = "Il tuo incantesimo viene interrotto",
    VIB_E_LOSSOFCONTROL = "Perdita di controllo (stordimento, paura, silenzio…)",
    VIB_E_AGGRO = "Prendi l'aggro",
    VIB_E_COMBAT = "Inizio del combattimento",
    VIB_E_PROC = "Proc di un incantesimo (evidenziato)",
    VIB_E_ACTIONFAILED = "Azione impossibile (portata, mana, bersaglio…)",
    VIB_E_WHISPER = "Sussurro ricevuto",
    VIB_E_INVITE = "Invito a gruppo o incursione",
    VIB_E_READYCHECK = "Appello (ready check)",
    VIB_E_REZSUMMON = "Resurrezione o evocazione proposta",
    VIB_E_TRADEDUEL = "Richiesta di scambio o duello",
    VIB_E_LEVELUP = "Salita di livello",
    VIB_E_QUEST = "Obiettivo o missione completati",
    VIB_E_RARELOOT = "Bottino raro o migliore",
    VIB_E_BAGSFULL = "Borse piene (messaggio del gioco)",
    VIB_E_DURABILITY = "Equipaggiamento quasi rotto",
    VIB_E_LOWSTOCK = "Scorte basse (munizioni, frammenti…)",
    VIB_E_LOWSPACE = "Poco spazio nelle borse",
    VIB_E_WHEELTICK = "Ruota: passaggio da una casella all'altra",
    VIB_E_KEYPRESS = "Tastiera della chat: tasto premuto",
    VIB_DIAG = "API di vibrazione: %s, controller: %s, la tua salute: %s, vibrazioni attive: %s",
    VIB_DIAG_HIDDEN = "nascosta dal gioco",
    VIB_DIAG_PATTERNS = "Schemi: %s",
    OLD_FOLDER = "|cffff6060La vecchia cartella ControllerKeyboard è ancora installata e viene caricata anch'essa.|r Elimina Interface/AddOns/ControllerKeyboard (a gioco chiuso): Easy Controller ora si trova in EasyController.",
    HELP = {
        "/ec - apri la tastiera",
        "/ec auto - apri automaticamente con la chat (attuale: %s)",
        "/ec pad - apri automaticamente solo se il controller è attivo (attuale: %s)",
        "/ec learn - impara le parole dai tuoi messaggi (attuale: %s)",
        "/ec lock - blocca/sblocca la posizione (attuale: %s)",
        "/ec mode wheel|stick - daisywheel o tastiera divisa",
        "/ec layout azerty|qwerty|qwertz|es|it - layout della tastiera divisa",
        "/ec lang fr|en|de|es|it|both - lingua dei suggerimenti e degli accenti",
        "/ec scale 0.8 - dimensione della tastiera",
        "/ec invert - inverti l'asse verticale dello stick",
        "/ec reset - riposiziona la tastiera",
        "/ec stats - statistiche di apprendimento",
        "/ec forget - dimentica tutte le parole apprese",
        "/ec glyphs - elenca le icone dei pulsanti del controller del gioco",
        "/ec config - configurazione (anche RB + croce giù)",
        "/ec map - mappatura del controller (pulsanti liberi, levette)",
        "/ec keys - mostra i tasti ricevuti dal gioco (levette)",
        "/ec vibe [schema] - provare la vibrazione del controller",
        "/ec debug - mostra i pulsanti ricevuti",
        "Opzioni: Esc > Opzioni > AddOns > Easy Controller - Forever",
    },
    ON = "|cff40ff40sì|r",
    OFF = "|cffff4040no|r",
    STATS = "%d parole apprese, %d parole nel dizionario.",
    FORGOT = "Parole apprese cancellate.",
    FORGET_CONFIRM = "Scrivi /ec forget confirm per cancellare tutte le parole apprese.",
    NO_DICT = "Dizionario non disponibile: %s",
    BINDING_TOGGLE = "Mostra/nascondi la tastiera",
    BADGE_HIDDEN = "Nascosto",
    BADGE_RIGHT = "A destra",
    BADGE_LEFT = "A sinistra",
    BADGE_BOTTOM = "Sotto",
    BADGE_TOP = "Sopra",
    BADGE_OUTER = "Lato esterno (sinistra / destra)",
    BADGE_OUTER_V = "Lato esterno (sopra / sotto)",
    OPT_BADGE = "Nome dei pulsanti extra (R4...)",
    PLACE_MOVING = "in spostamento",
    PLACE_P_CANCEL = "Annulla",
    PLACE_P_DROP = "Posa",
    PLACE_P_GRAB = "Prendi",
    PLACE_P_SELECT = "Scegli",
    MAP_SLOT_HINT = "Casella della barra del controller del gioco: A per metterci un incantesimo, un oggetto o una macro (come l'editor del gioco), X per svuotarla.",
    FEAT_RT_MODIFIER = "RT funge da modificatore: funzioni del gioco anche su RT + levette",
    FEAT_RT_MODIFIER_TIP = "Senza, RT + una levetta accetta incantesimi, oggetti e macro. Con (l'opzione del controller del gioco «RT emula Alt», o Ctrl, come LT invia già Maiusc), RT + una levetta diventa un tasto a sé e accetta anche le funzioni del gioco. La barra RT del gioco continua a funzionare.",
    FEAT_QUEST_GLOW = "Bordo arancione sugli oggetti richiesti da una missione nelle borse (quelli che il gioco non segna)",
    MAP_P_CONFIRM = "Conferma",
    PLACE_BAR = "Barra del controller",
    PLACE_P_PLACE = "Posto",
    FEAT_SHOW_STICKS = "Mostra L3 e R3 accanto alla barra, con la loro azione (corsa automatica, ping...)",
    FEAT_SHORTCUT = "Scorciatoia del controller per aprire questo pannello",
    CFG_SHORTCUT_KEY = "Combinazione: %s (A per cambiarla)",
    CFG_SHORTCUT_PRESS = "Tieni premuto un pulsante e premine un secondo... (Esc o B da solo: annulla)",
    CFG_SHORTCUT_RESET = "Torna a %s",
    CFG_TAB_GENERAL = "Generale",
    CFG_TAB_KEYBOARD = "Tastiera",
    CFG_TAB_GAMEPAD = "Controller",
    CFG_P_CHANGE = "Cambia",
    CFG_OPEN = "Apri la configurazione",
    CFG_OPEN_LATER = "Il pannello di Easy Controller - Forever si aprirà quando torni in gioco (opzioni e menu di gioco chiusi).",
    CFG_SETTINGS_HINT = "Tutte le impostazioni sono nel pannello dell'addon, con il controller o il mouse: RB + croce giù, /ec config o la sua scorciatoia.",
    CFG_H_FEATURES = "Funzioni",
    FEAT_DRAFTS = "Tieni il messaggio come bozza quando il gioco chiude la chat",
    FEAT_LINKS = "Aggiungi al messaggio i link di Maiusc+clic e «Condividi nella chat»",
    FEAT_QUEST_TOOLTIP = "Riga arancione «non vendere» nei tooltip",
    FEAT_QUEST_SELL = "Avviso quando si vende un oggetto di missione",
    FEAT_QUEST_HOVER = "Avviso selezionando un oggetto di missione da un mercante (borse del controller senza tooltip)",
    FEAT_EXTRA_DISPLAY = "Mostra i pulsanti extra accanto alla barra delle azioni del controller",
    MAP_IDENTIFY = "Identifica le levette posteriori",
    MAP_IDENTIFY_HINT = "Premi ogni levetta posteriore quando richiesto, così l'addon sa quale tasto o pulsante invia (assegna prima dei tasti della tastiera alle levette in Steam Input).",
    MAP_PLACE = "Posiziona barra e pulsanti",
    MAP_PLACE_HINT = "Sposta a scatti la barra del controller del gioco e posiziona ogni pulsante extra (levette, L3, R3) intorno, direttamente sullo schermo.",
    MAP_WIZARD = "Premi ora la levetta %s.",
    MAP_WIZARD_DONE = "Levette posteriori identificate.",
    MAP_P_SKIP = "Salta",
    MAP_P_SECTION = "Sezione",
    MAP_P_LIST = "Elenco",
    PLACE_TITLE = "Posiziona barra e pulsanti",
    PLACE_P_BUTTON = "Elemento",
    PLACE_P_SYM = "Simmetria: %s",
    PLACE_P_RESET = "Posto predefinito",
    PLACE_P_DONE = "Fine",
    BINDING_CONFIG = "Configurazione di Easy Controller - Forever",
    MOD_MAPPING = "Controller: funzioni extra sui pulsanti liberi e sulle levette posteriori",
    MAP_TITLE = "Mappatura del controller",
    MAP_ALONE = "Da solo",
    MAP_FREE = "Libero",
    MAP_GAME = "Gioco",
    MAP_EMPTY_SLOT = "vuoto",
    MAP_BACK_ROW = "Levette posteriori",
    MAP_LOCKED = "Nessun livello qui: questo grilletto non è un modificatore nelle impostazioni del controller del gioco, il pulsante fa lo stesso che senza.",
    MAP_SHARED_HINT = "Stesso tasto che senza il grilletto (non è un modificatore): incantesimi, oggetti e macro. Per le funzioni del gioco, rendi RT un modificatore (scheda Generale).",
    MAP_SHARED_LOCKED = "Stesso tasto di %s, che esegue una funzione del gioco (%s): una funzione del gioco occupa il tasto in tutti i suoi livelli. Mettici un incantesimo, un oggetto o una macro, oppure rendi RT un modificatore (scheda Generale).",
    MAP_SHARED_INACTIVE = "Non attiva: una funzione del gioco ha bisogno di un tasto suo, e questo livello condivide il tasto della levetta (il grilletto non è un modificatore). Rendi RT un modificatore (scheda Generale), oppure scegli un incantesimo, un oggetto o una macro.",
    MAP_NATIVE_HINT = "Funzione fissa del gioco, resta com'è.",
    MAP_FREE_HINT = "Libero: A per dargli una funzione.",
    MAP_ASSIGNED_HINT = "Aggiunto da Easy Controller (X per rimuovere).",
    MAP_PADDLE_KEY = "Tasto della levetta: %s (Y per impararlo di nuovo)",
    MAP_PADDLE_PRESS = "Premi ora la levetta... (B per annullare)",
    MAP_NOTHING = "Niente qui",
    MAP_TAB_GAME = "Gioco",
    MAP_TAB_SPELLS = "Incantesimi",
    MAP_TAB_ITEMS = "Oggetti",
    MAP_TAB_MACROS = "Macro",
    MAP_TAB_BAR = "Barra",
    MAP_P_MOVE = "Muovi",
    MAP_P_CHOOSE = "Scegli",
    MAP_P_CLEAR = "Rimuovi",
    MAP_P_KEY = "Tasto levetta",
    MAP_P_LAYER = "Livello",
    MAP_P_CLOSE = "Chiudi",
    MAP_P_BACK = "Indietro",
    MAP_P_TAB = "Scheda",
    NAT_JUMP = "Salta",
    NAT_INTERACT = "Interagisci",
    NAT_BACK = "Indietro",
    NAT_INSPECT = "Ispeziona",
    NAT_TARGET_FRIEND = "Bersaglia alleati",
    NAT_TARGET_ENEMY = "Bersaglia nemici",
    NAT_LAYER_LEFT = "Barra sinistra",
    NAT_LAYER_RIGHT = "Barra destra",
    NAT_START = "Menu Start",
    NAT_SELECT = "Focus dell'interfaccia",
    NAT_PING = "Ping",
    BINDING_MAP = "Mappatura del controller",
    PADDLE_KEY_REPLACES = "%s era assegnato a «%s»: la levetta lo sostituisce.",
    CAT_COMMON = "Scorciatoie comuni",
    DETECT_START = "Premi ora ogni levetta posteriore (L4, R4, L5, R5): i tasti ricevuti vengono mostrati per %d secondi.",
    DETECT_KEY = "Tasto ricevuto: %s",
    DETECT_PAD = "Pulsante del controller ricevuto: %s",
    DETECT_END = "Rilevamento dei tasti terminato.",
    QUEST_ITEM_TIP = "Oggetto di missione: non vendere",
    QUEST_ITEM_FOR = "Oggetto di missione (%s): non vendere",
    QUEST_ITEM_SOLD = "Oggetto di missione venduto: %s. Ricompralo nella scheda Riacquista del mercante.",
    QUEST_ITEM_SOLD_SHORT = "Oggetto di missione venduto! Vedi Riacquista",
    NO_QUESTS = "Nessuna missione in corso",
    QUESTS_TIP = "Missioni: inserisci un link di missione",
    KEYBOARD_OFF = "La tastiera è disattivata (Opzioni > AddOns > Easy Controller - Forever > Moduli).",
    MOD_KEYBOARD = "Tastiera (daisywheel / tastiera divisa)",
    MOD_QUEST_ITEMS = "Oggetti di missione: «non vendere» nei tooltip, avviso dal mercante",
    MOD_QUEST_LINKS = "Link di missione nella tastiera (e link con Maiusc+clic)",
}

for key, value in pairs(LOCALES[GetLocale()] or {}) do
    L[key] = value
end

BINDING_HEADER_CONTROLLERKEYBOARD = "Easy Controller - Forever"
BINDING_NAME_CONTROLLERKEYBOARD_TOGGLE = L.BINDING_TOGGLE
BINDING_NAME_CONTROLLERKEYBOARD_MAP = L.BINDING_MAP
BINDING_NAME_CONTROLLERKEYBOARD_CONFIG = L.BINDING_CONFIG
_G["BINDING_NAME_CLICK ControllerKeyboardWheelToggle:LeftButton"] = L.WHEEL_NAME

---------------------------------------------------------------------------
-- Saved variables
---------------------------------------------------------------------------
CK.DEFAULT_SHORTCUT = { hold = "PADRSHOULDER", press = "PADDDOWN" }

local DEFAULTS = {
    autoOpen = true,
    onlyWithGamepad = false,
    learn = true,
    -- Suggestions and keyboard layout follow the client's language by default
    lang = ({ frFR = "fr", deDE = "de", esES = "es", esMX = "es", itIT = "it" })[GetLocale()] or "en",
    maxWords = 8000,
    numSuggestions = 5,
    scale = 1,
    invertY = false,
    locked = true,
    -- Modules, each one can be turned off
    modules = { keyboard = true, questItems = true, questLinks = true, mapping = true },
    -- Gamepad mapping: ["L3:LT"] = "cmd:TOGGLERUN" | "spell:133" | "item:5512" | "macro:Name" | "bar:bottom:a"
    mapping = {},
    -- Back paddles' learned keys: { key = "F13" }
    paddles = { L4 = {}, L5 = {}, R4 = {}, R5 = {} },
    -- Each function can be turned off (General tab)
    features = {
        drafts = true, linkCapture = true,
        questTooltip = true, questGlow = true, questSellAlert = true, questHoverAlert = true,
        extraDisplay = true, showSticks = true, configShortcut = true,
    },
    -- Vibrations: one switch and intensity, then each event { on, pattern }
    -- (Vibration.lua fills the events)
    vibration = { enabled = true, intensity = 0.6, events = {} },
    -- Supplies: the buttons' bar (pos = { point, x, y }, size 1-3), each
    -- resource { on, low, critical } and the items added
    supplies = { enabled = true, locked = true, layout = "right", size = 2, list = {}, custom = {} },
    -- Consumables wheel: its kinds, and the variants beside the best of each
    wheel = {
        enabled = true, variants = true, locked = true,
        categories = { food = true, drink = true, healthPotion = true, manaPotion = true, healthstone = true,
            manaGem = true, bandage = true, buffFood = true, elixir = true, scroll = true },
    },
    -- Extra buttons' places ({ x, y } from the game's left / right bar), mirrored
    extraPos = {},
    -- The game's gamepad bar, moved by steps (0, 0: the game's own place)
    barOffset = { x = 0, y = 0 },
    -- The configuration panel's shortcut: a button held, another pressed
    shortcut = { hold = "PADRSHOULDER", press = "PADDDOWN" },
    extraSymmetric = true,
    badgePlace = "outer",    -- "R4" on the extra buttons: outer / top / bottom / left / right / hidden
    inputMethod = "wheel",   -- "wheel" (daisywheel) or "stick" (split keyboard)
    kbLayout = ({ frFR = "azerty", deDE = "qwertz", esES = "qwerty_es", esMX = "qwerty_es",
        itIT = "qwerty_it" })[GetLocale()] or "qwerty",
    deadzone = 0.15,         -- split keyboard: sticks dead zone
    stickCurve = "linear",   -- split keyboard: linear / gentle / fast
    magnet = "medium",       -- split keyboard: none / weak / medium / strong
    showLine = true,         -- split keyboard: lines from the centers to the cursors
    showActions = true,
    stickyChannel = true,    -- the channel row also sets the chat's own sticky channel
    font = "friz",
    glyphStyle = "xbox",
    gameGlyphs = true,
    debug = false,
}

local function copyDefaults(src, dst)
    for k, v in pairs(src) do
        if type(v) == "table" then
            if type(dst[k]) ~= "table" then dst[k] = {} end
            copyDefaults(v, dst[k])
        elseif dst[k] == nil then
            dst[k] = v
        end
    end
end

function CK:InitDB()
    ControllerKeyboardDB = ControllerKeyboardDB or {}
    local db = ControllerKeyboardDB
    db.settings = db.settings or {}
    -- Before 0.4.2: dicts = { frFR = bool, enUS = bool } instead of a language
    if db.settings.lang == nil and type(db.settings.dicts) == "table" then
        local d = db.settings.dicts
        db.settings.lang = (d.frFR and d.enUS) and "fren" or (d.enUS and "en") or "fr"
    end
    copyDefaults(DEFAULTS, db.settings)
    -- v2: auto-open no longer requires the gamepad to be the active input
    if (db.version or 1) < 2 then
        db.settings.onlyWithGamepad = false
        db.pos = nil
        db.version = 2
    end
    self.db = db
    self:ApplyLanguage()
    db.words = db.words or {}
    db.commands = db.commands or {}
    db.trigrams = db.trigrams or {}
    db.starts = db.starts or {}
    db.bigrams = db.bigrams or {}
    self.db = db
end

function CK:Print(msg, ...)
    if select("#", ...) > 0 then msg = format(msg, ...) end
    DEFAULT_CHAT_FRAME:AddMessage("|cff33ccffEasy Controller|r: " .. tostring(msg))
end

---------------------------------------------------------------------------
-- UTF-8 helpers (French accents)
---------------------------------------------------------------------------
local UTF8_2 = "[\195\197][\128-\191]"

local LOWER = {
    ["À"] = "à", ["Â"] = "â", ["Ä"] = "ä", ["Á"] = "á", ["Ç"] = "ç", ["É"] = "é", ["È"] = "è",
    ["Ê"] = "ê", ["Ë"] = "ë", ["Î"] = "î", ["Ï"] = "ï", ["Í"] = "í", ["Ô"] = "ô", ["Ö"] = "ö",
    ["Ó"] = "ó", ["Ò"] = "ò", ["Ì"] = "ì", ["Ù"] = "ù", ["Û"] = "û", ["Ü"] = "ü", ["Ú"] = "ú", ["Ÿ"] = "ÿ", ["Ñ"] = "ñ",
    ["Œ"] = "œ", ["Æ"] = "æ",
}
local UPPER = {}
for up, low in pairs(LOWER) do UPPER[low] = up end

local STRIP = {
    ["à"] = "a", ["â"] = "a", ["ä"] = "a", ["á"] = "a", ["ç"] = "c", ["é"] = "e", ["è"] = "e",
    ["ê"] = "e", ["ë"] = "e", ["î"] = "i", ["ï"] = "i", ["í"] = "i", ["ô"] = "o", ["ö"] = "o",
    ["ó"] = "o", ["ò"] = "o", ["ì"] = "i", ["ß"] = "ss", ["ù"] = "u", ["û"] = "u", ["ü"] = "u", ["ú"] = "u", ["ÿ"] = "y", ["ñ"] = "n",
    ["œ"] = "oe", ["æ"] = "ae",
}

-- string.lower/upper may touch UTF-8 bytes depending on the C locale: only map A-Z
local ASCII_LOWER, ASCII_UPPER = {}, {}
for b = 65, 90 do
    ASCII_LOWER[string.char(b)] = string.char(b + 32)
    ASCII_UPPER[string.char(b + 32)] = string.char(b)
end

function CK.Lower(s)
    return (s:gsub("[A-Z]", ASCII_LOWER):gsub(UTF8_2, LOWER))
end

function CK.Upper(s)
    return (s:gsub("[a-z]", ASCII_UPPER):gsub(UTF8_2, UPPER))
end

-- Lowercase and strip accents: "Été" -> "ete"
function CK.Normalize(s)
    return (CK.Lower(s):gsub(UTF8_2, STRIP))
end

function CK.FirstChar(s)
    return s:match("^[\192-\255][\128-\191]*") or s:sub(1, 1)
end

function CK.IsUpperInitial(s)
    local c = CK.FirstChar(s)
    return c ~= "" and c ~= CK.Lower(c)
end

function CK.Capitalize(s)
    local c = CK.FirstChar(s)
    return CK.Upper(c) .. s:sub(#c + 1)
end

---------------------------------------------------------------------------
-- Languages: dictionaries, and the accents of the 123 layer
---------------------------------------------------------------------------
CK.LANGUAGES = {
    { key = "fr", name = "Français", dicts = { "frFR" }, accents = "fr" },
    { key = "en", name = "English", dicts = { "enUS" }, accents = "en" },
    { key = "de", name = "Deutsch", dicts = { "deDE" }, accents = "de" },
    { key = "es", name = "Español", dicts = { "esES" }, accents = "es" },
    { key = "it", name = "Italiano", dicts = { "itIT" }, accents = "it" },
    { key = "fren", name = "Français + English", dicts = { "frFR", "enUS" }, accents = "fr" },
}

-- 12 characters per language: the accents first, then useful punctuation
CK.ACCENTS = {
    fr = { "é", "è", "ê", "à", "â", "ç", "ù", "û", "î", "ô", "ë", "ï" },
    en = { "é", "è", "à", "ç", "'", "?", "!", "-", "&", "$", "ë", "ï" },
    de = { "ä", "ö", "ü", "ß", "?", "!", "'", "-", "€", "&", "§", "_" },
    es = { "á", "é", "í", "ó", "ú", "ñ", "ü", "¿", "¡", "'", "-", "ç" },
    it = { "à", "è", "é", "ì", "ò", "ù", "ó", "í", "ú", "'", "?", "!" },
}

function CK:GetLanguage()
    local key = self.db and self.db.settings.lang
    for _, lang in ipairs(CK.LANGUAGES) do
        if lang.key == key then return lang end
    end
    return CK.LANGUAGES[2]
end

function CK:Accents()
    return CK.ACCENTS[self:GetLanguage().accents] or CK.ACCENTS.fr
end

-- The dictionaries in use come from the language
function CK:ApplyLanguage()
    local dicts = {}
    for _, key in ipairs(self:GetLanguage().dicts) do dicts[key] = true end
    self.db.settings.dicts = dicts
end

function CK:SetLanguage(key)
    self.db.settings.lang = key
    self:ApplyLanguage()
    CK.Predict:Load()
    if self.frame then self:UpdateMethod() end
end

-- Remove the last UTF-8 character of a string
function CK.DropLastChar(s)
    local i = #s
    while i > 1 do
        local b = s:byte(i)
        if b < 128 or b >= 192 then break end
        i = i - 1
    end
    return s:sub(1, i - 1)
end

-- Letters (ASCII + any UTF-8 byte) form words
CK.WORD_CHARS = "[%a\128-\255]"
