local ADDON, CK = ...
_G.ControllerKeyboard = CK

CK.ADDON = ADDON
CK.Dicts = CK.Dicts or {}

---------------------------------------------------------------------------
-- Localisation: English is the base, each client language overrides it
---------------------------------------------------------------------------
local L = {
    SHIFT = "Shift",
    SYMBOLS = "123",
    LETTERS = "abc",
    SPACE = "Space",
    BACKSPACE = "Delete",
    SEND = "Send",
    SEND_COMBAT = "Keyboard opened in combat: press Enter to send.",
    DRAG_HINT = "Drag to move the keyboard (/ck lock to lock)",
    LOCKED = "Position locked: %s",
    TEXTURES_MISSING = "|cffff4040Textures not found|r: quit and restart the game (/reload is not enough for new files).",
    COMBAT_UNAVAILABLE = "Not possible in combat",
    HELP_PETAL = "Petal",
    HELP_LETTER = "Letter",
    HELP_CHANNEL = "Channel",
    HELP_PICK = "Select",
    HELP_CURSOR_L = "Left cursor",
    HELP_CURSOR_R = "Right cursor",
    HELP_TYPE_L = "Type left",
    HELP_TYPE_R = "Type right",
    OPT_INPUT = "Input",
    OPT_METHOD = "Input method",
    METHOD_WHEEL = "Daisywheel",
    METHOD_STICK = "Split keyboard",
    OPT_LAYOUT = "Layout (split keyboard)",
    OPT_DEADZONE = "Stick dead zone",
    OPT_MAGNET = "Magnet",
    OPT_CURVE = "Stick response",
    CURVE_LINEAR = "Linear",
    CURVE_GENTLE = "Gentle (precise near the center)",
    CURVE_FAST = "Fast",
    MAGNET_NONE = "None",
    MAGNET_WEAK = "Weak",
    MAGNET_MEDIUM = "Medium",
    MAGNET_STRONG = "Strong",
    OPT_LINE = "Show the cursor line",
    MODE_SET = "Input method: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Language: %s",
    REPLY_TO = "Reply to %s: ",
    WHISPER_NAME = "Whisper to (name, then A): ",
    CHANNEL_NAMES = { "Say", "Yell", "Party", "Raid", "Guild", "General (/1)", "Whisper", "Reply" },
    CHANNEL_UNAVAILABLE = "unavailable",
    BADGE_SHIFT = "SHIFT",
    BADGE_CAPS = "CAPS",
    FONT_CHAT = "Chat font",
    GLYPHS_NONE = "No gamepad button atlas found: the addon's glyphs are used.",
    GLYPHS_FOUND = "%d gamepad button atlases found:",
    OPT_SUBTITLE = "On-screen keyboard to type in chat with a gamepad or the mouse.",
    OPT_KEYBOARD = "Keyboard",
    OPT_LOCK = "Lock position",
    OPT_AUTO = "Open automatically with the chat",
    OPT_PAD_ONLY = "Only when the gamepad is active",
    OPT_INVERT = "Invert the sticks vertical axis",
    OPT_SCALE = "Keyboard size",
    SIZE_SMALL = "Small",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Large",
    SIZE_XL = "Extra large",
    OPT_ACTIONS = "Show the mouse buttons (Shift, 123, Space, Delete, Send, X)",
    OPT_STICKY = "The chosen channel becomes the chat's own (like typing /p in game)",
    OPT_LOOK = "Look",
    OPT_FONT = "Font",
    OPT_GLYPHS = "Button glyphs",
    OPT_GAME_GLYPHS = "Use the game's button icons when available",
    OPT_PREDICTION = "Prediction",
    OPT_LANG = "Suggestion language",
    OPT_LEARN = "Learn from my messages",
    OPT_RESET_POS = "Reset keyboard position",
    OPT_FORGET = "Forget learned words",
    OPT_FORGET_CONFIRM = "Click again to confirm",
    LOADED = "v%s loaded. /ck for help.",
    HELP = {
        "/ck - open the keyboard",
        "/ck auto - open automatically with the chat (current: %s)",
        "/ck pad - only auto-open when the gamepad is active (current: %s)",
        "/ck learn - learn words from your messages (current: %s)",
        "/ck lock - lock/unlock the position (current: %s)",
        "/ck mode wheel|stick - daisywheel or split keyboard",
        "/ck layout azerty|qwerty|qwertz|es|it - split keyboard layout",
        "/ck lang fr|en|de|es|it|both - suggestion and accent language",
        "/ck scale 0.8 - keyboard size",
        "/ck invert - invert the stick vertical axis",
        "/ck reset - reset keyboard position",
        "/ck stats - learning statistics",
        "/ck forget - forget all learned words",
        "/ck glyphs - list the game's gamepad button icons",
        "/ck config - configuration (also RB + D-pad down)",
        "/ck map - gamepad mapping (free buttons, back paddles)",
        "/ck keys - show the keys the game receives (back paddles)",
        "/ck debug - print received buttons",
        "Options: Escape > Options > AddOns > Controller Keyboard",
    },
    ON = "|cff40ff40on|r",
    OFF = "|cffff4040off|r",
    STATS = "%d learned words, %d dictionary words.",
    FORGOT = "Learned words cleared.",
    FORGET_CONFIRM = "Type /ck forget confirm to clear all learned words.",
    NO_DICT = "Dictionary not available: %s",
    BINDING_TOGGLE = "Toggle keyboard",
    BADGE_HIDDEN = "Hidden",
    BADGE_RIGHT = "Right",
    BADGE_LEFT = "Left",
    BADGE_BOTTOM = "Below",
    BADGE_TOP = "Above",
    BADGE_OUTER = "Outer side",
    OPT_BADGE = "Name of the extra buttons (R4...)",
    PLACE_MOVING = "moving",
    PLACE_P_CANCEL = "Cancel",
    PLACE_P_DROP = "Put down",
    PLACE_P_GRAB = "Pick up",
    PLACE_P_SELECT = "Select",
    MAP_SLOT_HINT = "A slot of the game's gamepad bar: A to put a spell, an item or a macro in it (like the game's own editor), X to empty it.",
    FEAT_RT_MODIFIER = "RT acts as a modifier: RT and LT + RT layers for the extra buttons",
    FEAT_RT_MODIFIER_TIP = "Sets the game's gamepad setting \"RT emulates Alt\" (or Ctrl), like LT already sends Shift: RT + a paddle then becomes a key of its own. The game's own RT bar still works.",
    FEAT_QUEST_GLOW = "Orange glow around quest items in the bags",
    MAP_P_CONFIRM = "Confirm",
    PLACE_BAR = "Gamepad bar",
    PLACE_P_PLACE = "Place",
    FEAT_SHOW_STICKS = "Show L3 and R3 next to the bar, with what they do (autorun, ping...)",
    FEAT_SHORTCUT = "Gamepad shortcut to open this panel",
    CFG_SHORTCUT_KEY = "Combination: %s (A to change)",
    CFG_SHORTCUT_PRESS = "Hold a button and press a second one... (Escape or B alone: cancel)",
    CFG_SHORTCUT_RESET = "Back to %s",
    CFG_TAB_GENERAL = "General",
    CFG_TAB_KEYBOARD = "Keyboard",
    CFG_TAB_GAMEPAD = "Gamepad",
    CFG_P_CHANGE = "Change",
    CFG_OPEN = "Open the configuration",
    CFG_OPEN_LATER = "The Controller Keyboard panel opens once you are back in the game (options and game menu closed).",
    CFG_SETTINGS_HINT = "Every setting is in the addon's own panel, driven with the gamepad or the mouse: RB + D-pad down, /ck config, or its key binding.",
    CFG_H_FEATURES = "Features",
    FEAT_DRAFTS = "Keep the message as a draft when the game closes the chat",
    FEAT_LINKS = "Add Shift+click and \"Share in chat\" links to the message",
    FEAT_QUEST_TOOLTIP = "Orange \"do not sell\" line in item tooltips",
    FEAT_QUEST_SELL = "Warning when a quest item is sold",
    FEAT_QUEST_HOVER = "Warning when a quest item is selected at a merchant (gamepad bags without tooltips)",
    FEAT_EXTRA_DISPLAY = "Show the extra buttons next to the gamepad action bar",
    MAP_IDENTIFY = "Identify the back paddles",
    MAP_IDENTIFY_HINT = "Press each back paddle when asked, to tell the addon which key or button it sends (set the paddles to keyboard keys in Steam Input first).",
    MAP_PLACE = "Place the bar and extra buttons",
    MAP_PLACE_HINT = "Move the game's gamepad bar by steps, and place each extra button (back paddles, L3, R3) around it, on the screen.",
    MAP_WIZARD = "Press the back paddle %s now.",
    MAP_WIZARD_DONE = "Back paddles identified.",
    MAP_P_SKIP = "Skip",
    MAP_P_SECTION = "Section",
    MAP_P_LIST = "List",
    PLACE_TITLE = "Place the bar and extra buttons",
    PLACE_P_BUTTON = "Element",
    PLACE_P_SYM = "Mirror: %s",
    PLACE_P_RESET = "Default place",
    PLACE_P_DONE = "Done",
    BINDING_CONFIG = "Controller Keyboard configuration",
    MOD_MAPPING = "Gamepad: extra functions on the free buttons and back paddles",
    MAP_TITLE = "Gamepad mapping",
    MAP_ALONE = "Alone",
    MAP_FREE = "Free",
    MAP_GAME = "Game",
    MAP_EMPTY_SLOT = "empty",
    MAP_BACK_ROW = "Back paddles",
    MAP_LOCKED = "No layer here: this trigger is not a modifier in the game's gamepad settings, the button does the same as without it.",
    MAP_NATIVE_HINT = "Fixed by the game, left as it is.",
    MAP_FREE_HINT = "Free: A to give it a function.",
    MAP_ASSIGNED_HINT = "Added by Controller Keyboard (X to remove).",
    MAP_PADDLE_KEY = "Paddle key: %s (Y to learn it again)",
    MAP_PADDLE_PRESS = "Press the paddle now... (B to cancel)",
    MAP_NOTHING = "Nothing here",
    MAP_TAB_GAME = "Game",
    MAP_TAB_SPELLS = "Spells",
    MAP_TAB_ITEMS = "Items",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Bar",
    MAP_P_MOVE = "Move",
    MAP_P_CHOOSE = "Choose",
    MAP_P_CLEAR = "Remove",
    MAP_P_KEY = "Paddle key",
    MAP_P_LAYER = "Layer",
    MAP_P_CLOSE = "Close",
    MAP_P_BACK = "Back",
    MAP_P_TAB = "Tab",
    NAT_JUMP = "Jump",
    NAT_INTERACT = "Interact",
    NAT_BACK = "Back",
    NAT_INSPECT = "Inspect",
    NAT_TARGET_FRIEND = "Target allies",
    NAT_TARGET_ENEMY = "Target enemies",
    NAT_LAYER_LEFT = "Left bar",
    NAT_LAYER_RIGHT = "Right bar",
    NAT_START = "Start menu",
    NAT_SELECT = "Interface focus",
    NAT_PING = "Ping",
    BINDING_MAP = "Gamepad mapping",
    PADDLE_KEY_REPLACES = "%s was bound to \"%s\": the paddle takes it over.",
    CAT_COMMON = "Common shortcuts",
    DETECT_START = "Press each back paddle (L4, R4, L5, R5) now: the keys received are listed for %d seconds.",
    DETECT_KEY = "Key received: %s",
    DETECT_PAD = "Gamepad button received: %s",
    DETECT_END = "Key detection over.",
    QUEST_ITEM_TIP = "Quest item: do not sell",
    QUEST_ITEM_SOLD = "Quest item sold: %s. Buy it back from the merchant's Buyback tab.",
    QUEST_ITEM_SOLD_SHORT = "Quest item sold! See the Buyback tab",
    NO_QUESTS = "No quest in progress",
    QUESTS_TIP = "Quests: insert a quest link",
    KEYBOARD_OFF = "The keyboard is turned off (Options > AddOns > Controller Keyboard > Modules).",
    MOD_KEYBOARD = "Keyboard (daisywheel / split keyboard)",
    MOD_QUEST_ITEMS = "Quest items: \"do not sell\" in tooltips, warning at merchants",
    MOD_QUEST_LINKS = "Quest links in the keyboard (and Shift+click links)",
}
CK.L = L

local LOCALES = {}

LOCALES.frFR = {
    SHIFT = "Maj",
    SPACE = "Espace",
    BACKSPACE = "Effacer",
    SEND = "Envoyer",
    SEND_COMBAT = "Clavier ouvert en combat : appuyez sur Entrée pour envoyer.",
    DRAG_HINT = "Glisser pour déplacer le clavier (/ck lock pour verrouiller)",
    LOCKED = "Position verrouillée : %s",
    TEXTURES_MISSING = "|cffff4040Textures introuvables|r : quittez et relancez le jeu (un /reload ne suffit pas pour de nouveaux fichiers).",
    COMBAT_UNAVAILABLE = "Impossible en combat",
    HELP_PETAL = "Pétale",
    HELP_LETTER = "Lettre",
    HELP_CHANNEL = "Canal",
    HELP_PICK = "Choisir",
    HELP_CURSOR_L = "Curseur G",
    HELP_CURSOR_R = "Curseur D",
    HELP_TYPE_L = "Taper G",
    HELP_TYPE_R = "Taper D",
    OPT_INPUT = "Saisie",
    OPT_METHOD = "Méthode de saisie",
    METHOD_STICK = "Clavier 2 sticks",
    OPT_LAYOUT = "Disposition (clavier 2 sticks)",
    OPT_DEADZONE = "Zone morte du stick",
    OPT_MAGNET = "Effet aimant",
    OPT_CURVE = "Réponse du stick",
    CURVE_LINEAR = "Linéaire",
    CURVE_GENTLE = "Douce (précise au centre)",
    CURVE_FAST = "Rapide",
    MAGNET_NONE = "Aucun",
    MAGNET_WEAK = "Faible",
    MAGNET_MEDIUM = "Moyen",
    MAGNET_STRONG = "Fort",
    OPT_LINE = "Afficher la ligne du curseur",
    MODE_SET = "Méthode de saisie : %s",
    LAYOUT_SET = "Disposition : %s",
    LANG_SET = "Langue : %s",
    REPLY_TO = "Répondre à %s : ",
    WHISPER_NAME = "Chuchoter à (nom, puis A) : ",
    CHANNEL_NAMES = { "Dire", "Crier", "Groupe", "Raid", "Guilde", "Général (/1)", "Chuchoter", "Répondre" },
    CHANNEL_UNAVAILABLE = "indisponible",
    BADGE_SHIFT = "MAJ",
    BADGE_CAPS = "VERR. MAJ",
    FONT_CHAT = "Police du chat",
    GLYPHS_NONE = "Aucun atlas de boutons manette trouvé : les glyphes de l'addon sont utilisés.",
    GLYPHS_FOUND = "%d atlas de boutons manette trouvés :",
    OPT_SUBTITLE = "Clavier à l'écran pour écrire dans le chat à la manette ou à la souris.",
    OPT_KEYBOARD = "Clavier",
    OPT_LOCK = "Verrouiller la position",
    OPT_AUTO = "Ouvrir automatiquement avec le chat",
    OPT_PAD_ONLY = "Seulement quand la manette est active",
    OPT_INVERT = "Inverser l'axe vertical des sticks",
    OPT_SCALE = "Taille du clavier",
    SIZE_SMALL = "Petite",
    SIZE_NORMAL = "Normale",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Très grande",
    OPT_ACTIONS = "Afficher les boutons souris (Maj, 123, Espace, Effacer, Envoyer, X)",
    OPT_STICKY = "Le canal choisi devient celui du chat (comme taper /p en jeu)",
    OPT_LOOK = "Apparence",
    OPT_FONT = "Police",
    OPT_GLYPHS = "Boutons affichés",
    OPT_GAME_GLYPHS = "Utiliser les icônes de boutons du jeu si disponibles",
    OPT_PREDICTION = "Prédiction",
    OPT_LANG = "Langue des suggestions",
    OPT_LEARN = "Apprendre de mes messages",
    OPT_RESET_POS = "Replacer le clavier",
    OPT_FORGET = "Oublier les mots appris",
    OPT_FORGET_CONFIRM = "Cliquer pour confirmer",
    LOADED = "v%s chargé. /ck pour l'aide.",
    HELP = {
        "/ck - ouvrir le clavier",
        "/ck auto - ouverture automatique avec le chat (actuel : %s)",
        "/ck pad - n'ouvrir automatiquement que si la manette est active (actuel : %s)",
        "/ck learn - apprendre les mots de vos messages (actuel : %s)",
        "/ck lock - verrouiller/déverrouiller la position (actuel : %s)",
        "/ck mode wheel|stick - daisywheel ou clavier 2 sticks",
        "/ck layout azerty|qwerty|qwertz|es|it - disposition du clavier 2 sticks",
        "/ck lang fr|en|de|es|it|both - langue des suggestions et des accents",
        "/ck scale 0.8 - taille du clavier",
        "/ck invert - inverser l'axe vertical du stick",
        "/ck reset - replacer le clavier",
        "/ck stats - statistiques d'apprentissage",
        "/ck forget - oublier tous les mots appris",
        "/ck glyphs - lister les icônes de boutons manette du jeu",
        "/ck config - configuration (aussi RB + croix bas)",
        "/ck map - mappage manette (touches libres, palettes)",
        "/ck keys - afficher les touches reçues par le jeu (palettes)",
        "/ck debug - afficher les boutons reçus",
        "Options : Échap > Options > AddOns > Controller Keyboard",
    },
    ON = "|cff40ff40oui|r",
    OFF = "|cffff4040non|r",
    STATS = "%d mots appris, %d mots dans le dictionnaire.",
    FORGOT = "Mots appris effacés.",
    FORGET_CONFIRM = "Tapez /ck forget confirm pour effacer tous les mots appris.",
    NO_DICT = "Dictionnaire indisponible : %s",
    BINDING_TOGGLE = "Ouvrir/fermer le clavier",
    BADGE_HIDDEN = "Masqué",
    BADGE_RIGHT = "À droite",
    BADGE_LEFT = "À gauche",
    BADGE_BOTTOM = "En dessous",
    BADGE_TOP = "Au-dessus",
    BADGE_OUTER = "Côté extérieur",
    OPT_BADGE = "Nom des touches en plus (R4...)",
    PLACE_MOVING = "en déplacement",
    PLACE_P_CANCEL = "Annuler",
    PLACE_P_DROP = "Poser",
    PLACE_P_GRAB = "Prendre",
    PLACE_P_SELECT = "Choisir",
    MAP_SLOT_HINT = "Case de la barre manette du jeu : A pour y placer un sort, un objet ou une macro (comme l'éditeur du jeu), X pour la vider.",
    FEAT_RT_MODIFIER = "RT agit comme modificateur : couches RT et LT + RT pour les touches en plus",
    FEAT_RT_MODIFIER_TIP = "Règle le paramètre manette du jeu « RT émule Alt » (ou Ctrl), comme LT envoie déjà Maj : RT + une palette devient alors une touche à part. La barre RT du jeu fonctionne toujours.",
    FEAT_QUEST_GLOW = "Halo orange autour des objets de quête dans les sacs",
    MAP_P_CONFIRM = "Valider",
    PLACE_BAR = "Barre manette",
    PLACE_P_PLACE = "Place",
    FEAT_SHOW_STICKS = "Afficher L3 et R3 près de la barre, avec leur action (course auto, ping...)",
    FEAT_SHORTCUT = "Raccourci manette pour ouvrir ce panneau",
    CFG_SHORTCUT_KEY = "Combinaison : %s (A pour changer)",
    CFG_SHORTCUT_PRESS = "Maintenez un bouton et appuyez sur un second... (Échap ou B seul : annuler)",
    CFG_SHORTCUT_RESET = "Revenir à %s",
    CFG_TAB_GENERAL = "Général",
    CFG_TAB_KEYBOARD = "Clavier",
    CFG_TAB_GAMEPAD = "Manette",
    CFG_P_CHANGE = "Changer",
    CFG_OPEN = "Ouvrir la configuration",
    CFG_OPEN_LATER = "Le panneau Controller Keyboard s'ouvrira quand vous serez revenu en jeu (options et menu du jeu fermés).",
    CFG_SETTINGS_HINT = "Tous les réglages sont dans le panneau de l'addon, à la manette ou à la souris : RB + croix bas, /ck config ou son raccourci.",
    CFG_H_FEATURES = "Fonctions",
    FEAT_DRAFTS = "Garder le message en brouillon quand le jeu ferme le chat",
    FEAT_LINKS = "Ajouter au message les liens Maj+clic et « Partager dans la discussion »",
    FEAT_QUEST_TOOLTIP = "Ligne orange « ne pas vendre » dans les info-bulles",
    FEAT_QUEST_SELL = "Alerte quand un objet de quête est vendu",
    FEAT_QUEST_HOVER = "Alerte en sélectionnant un objet de quête chez un marchand (sacs manette sans info-bulles)",
    FEAT_EXTRA_DISPLAY = "Afficher les touches en plus à côté de la barre d'action manette",
    MAP_IDENTIFY = "Identifier les palettes arrière",
    MAP_IDENTIFY_HINT = "Appuyez sur chaque palette quand elle est demandée, pour que l'addon sache quelle touche ou quel bouton elle envoie (assignez d'abord des touches clavier aux palettes dans Steam Input).",
    MAP_PLACE = "Placer la barre et les touches",
    MAP_PLACE_HINT = "Déplacez la barre manette du jeu par crans, et placez chaque touche en plus (palettes, L3, R3) autour, directement à l'écran.",
    MAP_WIZARD = "Appuyez maintenant sur la palette %s.",
    MAP_WIZARD_DONE = "Palettes arrière identifiées.",
    MAP_P_SKIP = "Passer",
    MAP_P_SECTION = "Section",
    MAP_P_LIST = "Liste",
    PLACE_TITLE = "Placer la barre et les touches",
    PLACE_P_BUTTON = "Élément",
    PLACE_P_SYM = "Symétrie : %s",
    PLACE_P_RESET = "Place par défaut",
    PLACE_P_DONE = "Terminer",
    BINDING_CONFIG = "Configuration de Controller Keyboard",
    MOD_MAPPING = "Manette : fonctions en plus sur les touches libres et les palettes arrière",
    MAP_TITLE = "Mappage manette",
    MAP_ALONE = "Seul",
    MAP_FREE = "Libre",
    MAP_GAME = "Jeu",
    MAP_EMPTY_SLOT = "vide",
    MAP_BACK_ROW = "Palettes arrière",
    MAP_LOCKED = "Pas de couche ici : cette gâchette n'est pas un modificateur dans les réglages manette du jeu, le bouton fait la même chose que sans elle.",
    MAP_NATIVE_HINT = "Fonction fixe du jeu, laissée telle quelle.",
    MAP_FREE_HINT = "Libre : A pour lui donner une fonction.",
    MAP_ASSIGNED_HINT = "Ajouté par Controller Keyboard (X pour retirer).",
    MAP_PADDLE_KEY = "Touche de la palette : %s (Y pour la réapprendre)",
    MAP_PADDLE_PRESS = "Appuyez maintenant sur la palette... (B pour annuler)",
    MAP_NOTHING = "Rien ici",
    MAP_TAB_GAME = "Jeu",
    MAP_TAB_SPELLS = "Sorts",
    MAP_TAB_ITEMS = "Objets",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Barre",
    MAP_P_MOVE = "Déplacer",
    MAP_P_CHOOSE = "Choisir",
    MAP_P_CLEAR = "Retirer",
    MAP_P_KEY = "Touche palette",
    MAP_P_LAYER = "Couche",
    MAP_P_CLOSE = "Fermer",
    MAP_P_BACK = "Retour",
    MAP_P_TAB = "Onglet",
    NAT_JUMP = "Sauter",
    NAT_INTERACT = "Interagir",
    NAT_BACK = "Retour",
    NAT_INSPECT = "Inspecter",
    NAT_TARGET_FRIEND = "Cibler les alliés",
    NAT_TARGET_ENEMY = "Cibler les ennemis",
    NAT_LAYER_LEFT = "Barre gauche",
    NAT_LAYER_RIGHT = "Barre droite",
    NAT_START = "Menu Start",
    NAT_SELECT = "Focus de l'interface",
    NAT_PING = "Ping",
    BINDING_MAP = "Mappage manette",
    PADDLE_KEY_REPLACES = "%s était lié à « %s » : la palette le remplace.",
    CAT_COMMON = "Raccourcis courants",
    DETECT_START = "Appuie maintenant sur chaque palette (L4, R4, L5, R5) : les touches reçues s'affichent pendant %d secondes.",
    DETECT_KEY = "Touche reçue : %s",
    DETECT_PAD = "Bouton manette reçu : %s",
    DETECT_END = "Détection des touches terminée.",
    QUEST_ITEM_TIP = "Objet de quête : ne pas vendre",
    QUEST_ITEM_SOLD = "Objet de quête vendu : %s. Rachetez-le dans l'onglet Rachat du marchand.",
    QUEST_ITEM_SOLD_SHORT = "Objet de quête vendu ! Voir l'onglet Rachat",
    NO_QUESTS = "Aucune quête en cours",
    QUESTS_TIP = "Quêtes : insérer un lien de quête",
    KEYBOARD_OFF = "Le clavier est désactivé (Options > AddOns > Controller Keyboard > Modules).",
    MOD_KEYBOARD = "Clavier (daisywheel / clavier 2 sticks)",
    MOD_QUEST_ITEMS = "Objets de quête : « ne pas vendre » dans les info-bulles, alerte chez le marchand",
    MOD_QUEST_LINKS = "Liens de quête dans le clavier (et liens par Maj+clic)",
}

LOCALES.deDE = {
    SHIFT = "Umschalt",
    SPACE = "Leertaste",
    BACKSPACE = "Löschen",
    SEND = "Senden",
    SEND_COMBAT = "Tastatur im Kampf geöffnet: zum Senden Enter drücken.",
    DRAG_HINT = "Ziehen, um die Tastatur zu verschieben (/ck lock zum Sperren)",
    LOCKED = "Position gesperrt: %s",
    TEXTURES_MISSING = "|cffff4040Texturen nicht gefunden|r: Spiel beenden und neu starten (/reload reicht für neue Dateien nicht).",
    COMBAT_UNAVAILABLE = "Im Kampf nicht möglich",
    HELP_PETAL = "Blatt",
    HELP_LETTER = "Buchstabe",
    HELP_CHANNEL = "Kanal",
    HELP_PICK = "Auswählen",
    HELP_CURSOR_L = "Cursor links",
    HELP_CURSOR_R = "Cursor rechts",
    HELP_TYPE_L = "Tippen links",
    HELP_TYPE_R = "Tippen rechts",
    OPT_INPUT = "Eingabe",
    OPT_METHOD = "Eingabemethode",
    METHOD_STICK = "Geteilte Tastatur",
    OPT_LAYOUT = "Layout (geteilte Tastatur)",
    OPT_DEADZONE = "Totzone des Sticks",
    OPT_MAGNET = "Magnetwirkung",
    OPT_CURVE = "Stick-Reaktion",
    CURVE_LINEAR = "Linear",
    CURVE_GENTLE = "Sanft (präzise in der Mitte)",
    CURVE_FAST = "Schnell",
    MAGNET_NONE = "Keine",
    MAGNET_WEAK = "Schwach",
    MAGNET_MEDIUM = "Mittel",
    MAGNET_STRONG = "Stark",
    OPT_LINE = "Cursorlinie anzeigen",
    MODE_SET = "Eingabemethode: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Sprache: %s",
    REPLY_TO = "Antwort an %s: ",
    WHISPER_NAME = "Flüstern an (Name, dann A): ",
    CHANNEL_NAMES = { "Sagen", "Schreien", "Gruppe", "Schlachtzug", "Gilde", "Allgemein (/1)", "Flüstern", "Antworten" },
    CHANNEL_UNAVAILABLE = "nicht verfügbar",
    BADGE_SHIFT = "UMSCH",
    BADGE_CAPS = "FESTSTELL",
    FONT_CHAT = "Chat-Schriftart",
    GLYPHS_NONE = "Keine Gamepad-Tastensymbole gefunden: die Symbole des Addons werden verwendet.",
    GLYPHS_FOUND = "%d Gamepad-Tastensymbole gefunden:",
    OPT_SUBTITLE = "Bildschirmtastatur, um mit dem Gamepad oder der Maus im Chat zu schreiben.",
    OPT_KEYBOARD = "Tastatur",
    OPT_LOCK = "Position sperren",
    OPT_AUTO = "Automatisch mit dem Chat öffnen",
    OPT_PAD_ONLY = "Nur wenn das Gamepad aktiv ist",
    OPT_INVERT = "Vertikale Stick-Achse umkehren",
    OPT_SCALE = "Tastaturgröße",
    SIZE_SMALL = "Klein",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Groß",
    SIZE_XL = "Sehr groß",
    OPT_ACTIONS = "Maustasten anzeigen (Umschalt, 123, Leertaste, Löschen, Senden, X)",
    OPT_STICKY = "Der gewählte Kanal wird zum Chatkanal (wie /p im Spiel)",
    OPT_LOOK = "Aussehen",
    OPT_FONT = "Schriftart",
    OPT_GLYPHS = "Tastensymbole",
    OPT_GAME_GLYPHS = "Tastensymbole des Spiels verwenden, falls verfügbar",
    OPT_PREDICTION = "Vorhersage",
    OPT_LANG = "Sprache der Vorschläge",
    OPT_LEARN = "Aus meinen Nachrichten lernen",
    OPT_RESET_POS = "Tastatur zurücksetzen",
    OPT_FORGET = "Gelernte Wörter vergessen",
    OPT_FORGET_CONFIRM = "Zum Bestätigen erneut klicken",
    LOADED = "v%s geladen. /ck für Hilfe.",
    HELP = {
        "/ck - Tastatur öffnen",
        "/ck auto - automatisch mit dem Chat öffnen (aktuell: %s)",
        "/ck pad - nur automatisch öffnen, wenn das Gamepad aktiv ist (aktuell: %s)",
        "/ck learn - Wörter aus deinen Nachrichten lernen (aktuell: %s)",
        "/ck lock - Position sperren/entsperren (aktuell: %s)",
        "/ck mode wheel|stick - Daisywheel oder geteilte Tastatur",
        "/ck layout azerty|qwerty|qwertz|es|it - Layout der geteilten Tastatur",
        "/ck lang fr|en|de|es|it|both - Sprache der Vorschläge und Akzente",
        "/ck scale 0.8 - Tastaturgröße",
        "/ck invert - vertikale Stick-Achse umkehren",
        "/ck reset - Tastatur zurücksetzen",
        "/ck stats - Lernstatistik",
        "/ck forget - alle gelernten Wörter vergessen",
        "/ck glyphs - Gamepad-Tastensymbole des Spiels auflisten",
        "/ck config - Konfiguration (auch RB + Steuerkreuz unten)",
        "/ck map - Gamepad-Belegung (freie Tasten, Paddles)",
        "/ck keys - vom Spiel empfangene Tasten anzeigen (Paddles)",
        "/ck debug - empfangene Tasten anzeigen",
        "Optionen: Esc > Optionen > AddOns > Controller Keyboard",
    },
    ON = "|cff40ff40an|r",
    OFF = "|cffff4040aus|r",
    STATS = "%d gelernte Wörter, %d Wörter im Wörterbuch.",
    FORGOT = "Gelernte Wörter gelöscht.",
    FORGET_CONFIRM = "Gib /ck forget confirm ein, um alle gelernten Wörter zu löschen.",
    NO_DICT = "Wörterbuch nicht verfügbar: %s",
    BINDING_TOGGLE = "Tastatur ein-/ausblenden",
    BADGE_HIDDEN = "Ausgeblendet",
    BADGE_RIGHT = "Rechts",
    BADGE_LEFT = "Links",
    BADGE_BOTTOM = "Unten",
    BADGE_TOP = "Oben",
    BADGE_OUTER = "Außenseite",
    OPT_BADGE = "Name der zusätzlichen Tasten (R4...)",
    PLACE_MOVING = "wird verschoben",
    PLACE_P_CANCEL = "Abbrechen",
    PLACE_P_DROP = "Ablegen",
    PLACE_P_GRAB = "Aufnehmen",
    PLACE_P_SELECT = "Wählen",
    MAP_SLOT_HINT = "Feld der Gamepad-Leiste des Spiels: A, um einen Zauber, einen Gegenstand oder ein Makro hineinzulegen (wie im Editor des Spiels), X zum Leeren.",
    FEAT_RT_MODIFIER = "RT als Modifikator: RT- und LT+RT-Ebenen für die zusätzlichen Tasten",
    FEAT_RT_MODIFIER_TIP = "Setzt die Gamepad-Einstellung des Spiels „RT emuliert Alt“ (oder Strg), so wie LT schon Umschalt sendet: RT + ein Paddle wird dann eine eigene Taste. Die RT-Leiste des Spiels funktioniert weiter.",
    FEAT_QUEST_GLOW = "Oranges Leuchten um Questgegenstände in den Taschen",
    MAP_P_CONFIRM = "Bestätigen",
    PLACE_BAR = "Gamepad-Leiste",
    PLACE_P_PLACE = "Platz",
    FEAT_SHOW_STICKS = "L3 und R3 neben der Leiste anzeigen, mit ihrer Aktion (Autolauf, Ping...)",
    FEAT_SHORTCUT = "Gamepad-Kürzel zum Öffnen dieses Fensters",
    CFG_SHORTCUT_KEY = "Kombination: %s (A zum Ändern)",
    CFG_SHORTCUT_PRESS = "Halte eine Taste und drücke eine zweite... (Escape oder B allein: abbrechen)",
    CFG_SHORTCUT_RESET = "Zurück zu %s",
    CFG_TAB_GENERAL = "Allgemein",
    CFG_TAB_KEYBOARD = "Tastatur",
    CFG_TAB_GAMEPAD = "Gamepad",
    CFG_P_CHANGE = "Ändern",
    CFG_OPEN = "Konfiguration öffnen",
    CFG_OPEN_LATER = "Das Controller-Keyboard-Fenster öffnet sich, sobald du wieder im Spiel bist (Optionen und Spielmenü geschlossen).",
    CFG_SETTINGS_HINT = "Alle Einstellungen sind im eigenen Fenster des Addons, per Gamepad oder Maus: RB + Steuerkreuz unten, /ck config oder seine Tastenbelegung.",
    CFG_H_FEATURES = "Funktionen",
    FEAT_DRAFTS = "Nachricht als Entwurf behalten, wenn das Spiel den Chat schließt",
    FEAT_LINKS = "Links per Umschalt+Klick und „Im Chat teilen“ zur Nachricht hinzufügen",
    FEAT_QUEST_TOOLTIP = "Orange Zeile „nicht verkaufen“ im Tooltip",
    FEAT_QUEST_SELL = "Warnung, wenn ein Questgegenstand verkauft wird",
    FEAT_QUEST_HOVER = "Warnung beim Auswählen eines Questgegenstands beim Händler (Gamepad-Taschen ohne Tooltips)",
    FEAT_EXTRA_DISPLAY = "Zusätzliche Tasten neben der Gamepad-Aktionsleiste anzeigen",
    MAP_IDENTIFY = "Hintere Paddles erkennen",
    MAP_IDENTIFY_HINT = "Drücke jedes hintere Paddle, wenn es verlangt wird, damit das Addon weiß, welche Taste es sendet (lege den Paddles zuerst in Steam Input Tastaturtasten fest).",
    MAP_PLACE = "Leiste und Tasten platzieren",
    MAP_PLACE_HINT = "Verschiebe die Gamepad-Leiste des Spiels schrittweise und platziere jede zusätzliche Taste (Paddles, L3, R3) direkt am Bildschirm darum herum.",
    MAP_WIZARD = "Drücke jetzt das Paddle %s.",
    MAP_WIZARD_DONE = "Hintere Paddles erkannt.",
    MAP_P_SKIP = "Überspringen",
    MAP_P_SECTION = "Abschnitt",
    MAP_P_LIST = "Liste",
    PLACE_TITLE = "Leiste und Tasten platzieren",
    PLACE_P_BUTTON = "Element",
    PLACE_P_SYM = "Spiegeln: %s",
    PLACE_P_RESET = "Standardplatz",
    PLACE_P_DONE = "Fertig",
    BINDING_CONFIG = "Controller-Keyboard-Konfiguration",
    MOD_MAPPING = "Gamepad: zusätzliche Funktionen auf freien Tasten und hinteren Paddles",
    MAP_TITLE = "Gamepad-Belegung",
    MAP_ALONE = "Allein",
    MAP_FREE = "Frei",
    MAP_GAME = "Spiel",
    MAP_EMPTY_SLOT = "leer",
    MAP_BACK_ROW = "Hintere Paddles",
    MAP_LOCKED = "Hier keine Ebene: dieser Abzug ist in den Gamepad-Einstellungen des Spiels kein Modifikator, die Taste tut dasselbe wie ohne ihn.",
    MAP_NATIVE_HINT = "Vom Spiel fest belegt, bleibt unverändert.",
    MAP_FREE_HINT = "Frei: A, um eine Funktion zuzuweisen.",
    MAP_ASSIGNED_HINT = "Von Controller Keyboard hinzugefügt (X zum Entfernen).",
    MAP_PADDLE_KEY = "Paddle-Taste: %s (Y zum erneuten Erlernen)",
    MAP_PADDLE_PRESS = "Drücke jetzt das Paddle... (B zum Abbrechen)",
    MAP_NOTHING = "Nichts hier",
    MAP_TAB_GAME = "Spiel",
    MAP_TAB_SPELLS = "Zauber",
    MAP_TAB_ITEMS = "Items",
    MAP_TAB_MACROS = "Makros",
    MAP_TAB_BAR = "Leiste",
    MAP_P_MOVE = "Bewegen",
    MAP_P_CHOOSE = "Wählen",
    MAP_P_CLEAR = "Entfernen",
    MAP_P_KEY = "Paddle-Taste",
    MAP_P_LAYER = "Ebene",
    MAP_P_CLOSE = "Schließen",
    MAP_P_BACK = "Zurück",
    MAP_P_TAB = "Reiter",
    NAT_JUMP = "Springen",
    NAT_INTERACT = "Interagieren",
    NAT_BACK = "Zurück",
    NAT_INSPECT = "Betrachten",
    NAT_TARGET_FRIEND = "Verbündete anvisieren",
    NAT_TARGET_ENEMY = "Feinde anvisieren",
    NAT_LAYER_LEFT = "Linke Leiste",
    NAT_LAYER_RIGHT = "Rechte Leiste",
    NAT_START = "Startmenü",
    NAT_SELECT = "Interface-Fokus",
    NAT_PING = "Ping",
    BINDING_MAP = "Gamepad-Belegung",
    PADDLE_KEY_REPLACES = "%s war mit „%s“ belegt: das Paddle übernimmt die Taste.",
    CAT_COMMON = "Häufige Tastenbelegungen",
    DETECT_START = "Drücke jetzt jedes hintere Paddle (L4, R4, L5, R5): die empfangenen Tasten werden %d Sekunden lang angezeigt.",
    DETECT_KEY = "Taste empfangen: %s",
    DETECT_PAD = "Gamepad-Taste empfangen: %s",
    DETECT_END = "Tastenerkennung beendet.",
    QUEST_ITEM_TIP = "Questgegenstand: nicht verkaufen",
    QUEST_ITEM_SOLD = "Questgegenstand verkauft: %s. Kaufe ihn im Rückkauf-Reiter des Händlers zurück.",
    QUEST_ITEM_SOLD_SHORT = "Questgegenstand verkauft! Siehe Rückkauf",
    NO_QUESTS = "Keine laufende Quest",
    QUESTS_TIP = "Quests: Questlink einfügen",
    KEYBOARD_OFF = "Die Tastatur ist ausgeschaltet (Optionen > AddOns > Controller Keyboard > Module).",
    MOD_KEYBOARD = "Tastatur (Daisywheel / geteilte Tastatur)",
    MOD_QUEST_ITEMS = "Questgegenstände: „nicht verkaufen“ im Tooltip, Warnung beim Händler",
    MOD_QUEST_LINKS = "Questlinks in der Tastatur (und Links per Umschalt+Klick)",
}

LOCALES.esES = {
    SHIFT = "Mayús",
    SPACE = "Espacio",
    BACKSPACE = "Borrar",
    SEND = "Enviar",
    SEND_COMBAT = "Teclado abierto en combate: pulsa Intro para enviar.",
    DRAG_HINT = "Arrastra para mover el teclado (/ck lock para bloquearlo)",
    LOCKED = "Posición bloqueada: %s",
    TEXTURES_MISSING = "|cffff4040Texturas no encontradas|r: cierra y reinicia el juego (/reload no basta para archivos nuevos).",
    COMBAT_UNAVAILABLE = "No es posible en combate",
    HELP_PETAL = "Pétalo",
    HELP_LETTER = "Letra",
    HELP_CHANNEL = "Canal",
    HELP_PICK = "Elegir",
    HELP_CURSOR_L = "Cursor izq.",
    HELP_CURSOR_R = "Cursor der.",
    HELP_TYPE_L = "Escribir izq.",
    HELP_TYPE_R = "Escribir der.",
    OPT_INPUT = "Escritura",
    OPT_METHOD = "Método de escritura",
    METHOD_STICK = "Teclado dividido",
    OPT_LAYOUT = "Distribución (teclado dividido)",
    OPT_DEADZONE = "Zona muerta del stick",
    OPT_MAGNET = "Efecto imán",
    OPT_CURVE = "Respuesta del stick",
    CURVE_LINEAR = "Lineal",
    CURVE_GENTLE = "Suave (precisa en el centro)",
    CURVE_FAST = "Rápida",
    MAGNET_NONE = "Ninguno",
    MAGNET_WEAK = "Débil",
    MAGNET_MEDIUM = "Medio",
    MAGNET_STRONG = "Fuerte",
    OPT_LINE = "Mostrar la línea del cursor",
    MODE_SET = "Método de escritura: %s",
    LAYOUT_SET = "Distribución: %s",
    LANG_SET = "Idioma: %s",
    REPLY_TO = "Responder a %s: ",
    WHISPER_NAME = "Susurrar a (nombre, luego A): ",
    CHANNEL_NAMES = { "Decir", "Gritar", "Grupo", "Banda", "Hermandad", "General (/1)", "Susurrar", "Responder" },
    CHANNEL_UNAVAILABLE = "no disponible",
    BADGE_SHIFT = "MAYÚS",
    BADGE_CAPS = "BLOQ MAYÚS",
    FONT_CHAT = "Fuente del chat",
    GLYPHS_NONE = "No se encontraron iconos de botones del mando: se usan los del addon.",
    GLYPHS_FOUND = "%d iconos de botones del mando encontrados:",
    OPT_SUBTITLE = "Teclado en pantalla para escribir en el chat con el mando o el ratón.",
    OPT_KEYBOARD = "Teclado",
    OPT_LOCK = "Bloquear la posición",
    OPT_AUTO = "Abrir automáticamente con el chat",
    OPT_PAD_ONLY = "Solo cuando el mando está activo",
    OPT_INVERT = "Invertir el eje vertical de los sticks",
    OPT_SCALE = "Tamaño del teclado",
    SIZE_SMALL = "Pequeño",
    SIZE_NORMAL = "Normal",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Muy grande",
    OPT_ACTIONS = "Mostrar los botones del ratón (Mayús, 123, Espacio, Borrar, Enviar, X)",
    OPT_STICKY = "El canal elegido pasa a ser el del chat (como escribir /p en el juego)",
    OPT_LOOK = "Apariencia",
    OPT_FONT = "Fuente",
    OPT_GLYPHS = "Iconos de botones",
    OPT_GAME_GLYPHS = "Usar los iconos de botones del juego si están disponibles",
    OPT_PREDICTION = "Predicción",
    OPT_LANG = "Idioma de las sugerencias",
    OPT_LEARN = "Aprender de mis mensajes",
    OPT_RESET_POS = "Recolocar el teclado",
    OPT_FORGET = "Olvidar las palabras aprendidas",
    OPT_FORGET_CONFIRM = "Pulsa otra vez para confirmar",
    LOADED = "v%s cargado. /ck para la ayuda.",
    HELP = {
        "/ck - abrir el teclado",
        "/ck auto - abrir automáticamente con el chat (actual: %s)",
        "/ck pad - abrir automáticamente solo si el mando está activo (actual: %s)",
        "/ck learn - aprender las palabras de tus mensajes (actual: %s)",
        "/ck lock - bloquear/desbloquear la posición (actual: %s)",
        "/ck mode wheel|stick - daisywheel o teclado dividido",
        "/ck layout azerty|qwerty|qwertz|es|it - distribución del teclado dividido",
        "/ck lang fr|en|de|es|it|both - idioma de las sugerencias y de los acentos",
        "/ck scale 0.8 - tamaño del teclado",
        "/ck invert - invertir el eje vertical del stick",
        "/ck reset - recolocar el teclado",
        "/ck stats - estadísticas de aprendizaje",
        "/ck forget - olvidar todas las palabras aprendidas",
        "/ck glyphs - listar los iconos de botones del mando del juego",
        "/ck config - configuración (también RB + cruceta abajo)",
        "/ck map - asignación del mando (botones libres, paletas)",
        "/ck keys - mostrar las teclas que recibe el juego (paletas)",
        "/ck debug - mostrar los botones recibidos",
        "Opciones: Esc > Opciones > AddOns > Controller Keyboard",
    },
    ON = "|cff40ff40sí|r",
    OFF = "|cffff4040no|r",
    STATS = "%d palabras aprendidas, %d palabras en el diccionario.",
    FORGOT = "Palabras aprendidas borradas.",
    FORGET_CONFIRM = "Escribe /ck forget confirm para borrar todas las palabras aprendidas.",
    NO_DICT = "Diccionario no disponible: %s",
    BINDING_TOGGLE = "Mostrar/ocultar el teclado",
    BADGE_HIDDEN = "Oculto",
    BADGE_RIGHT = "A la derecha",
    BADGE_LEFT = "A la izquierda",
    BADGE_BOTTOM = "Abajo",
    BADGE_TOP = "Arriba",
    BADGE_OUTER = "Lado exterior",
    OPT_BADGE = "Nombre de los botones extra (R4...)",
    PLACE_MOVING = "moviéndose",
    PLACE_P_CANCEL = "Cancelar",
    PLACE_P_DROP = "Soltar",
    PLACE_P_GRAB = "Coger",
    PLACE_P_SELECT = "Elegir",
    MAP_SLOT_HINT = "Casilla de la barra del mando del juego: A para poner un hechizo, un objeto o una macro (como el editor del juego), X para vaciarla.",
    FEAT_RT_MODIFIER = "RT actúa como modificador: capas RT y LT + RT para los botones extra",
    FEAT_RT_MODIFIER_TIP = "Activa el ajuste del mando del juego «RT emula Alt» (o Ctrl), como LT ya envía Mayús: RT + una paleta se convierte en una tecla propia. La barra RT del juego sigue funcionando.",
    FEAT_QUEST_GLOW = "Brillo naranja alrededor de los objetos de misión en las bolsas",
    MAP_P_CONFIRM = "Confirmar",
    PLACE_BAR = "Barra del mando",
    PLACE_P_PLACE = "Sitio",
    FEAT_SHOW_STICKS = "Mostrar L3 y R3 junto a la barra, con su acción (correr automático, ping...)",
    FEAT_SHORTCUT = "Atajo del mando para abrir este panel",
    CFG_SHORTCUT_KEY = "Combinación: %s (A para cambiarla)",
    CFG_SHORTCUT_PRESS = "Mantén un botón y pulsa un segundo... (Escape o B solo: cancelar)",
    CFG_SHORTCUT_RESET = "Volver a %s",
    CFG_TAB_GENERAL = "General",
    CFG_TAB_KEYBOARD = "Teclado",
    CFG_TAB_GAMEPAD = "Mando",
    CFG_P_CHANGE = "Cambiar",
    CFG_OPEN = "Abrir la configuración",
    CFG_OPEN_LATER = "El panel de Controller Keyboard se abrirá cuando vuelvas al juego (opciones y menú del juego cerrados).",
    CFG_SETTINGS_HINT = "Todos los ajustes están en el panel del addon, con el mando o el ratón: RB + cruceta abajo, /ck config o su atajo.",
    CFG_H_FEATURES = "Funciones",
    FEAT_DRAFTS = "Guardar el mensaje como borrador cuando el juego cierra el chat",
    FEAT_LINKS = "Añadir al mensaje los enlaces de Mayús+clic y «Compartir en el chat»",
    FEAT_QUEST_TOOLTIP = "Línea naranja «no vender» en las descripciones",
    FEAT_QUEST_SELL = "Aviso al vender un objeto de misión",
    FEAT_QUEST_HOVER = "Aviso al seleccionar un objeto de misión en un vendedor (bolsas del mando sin descripciones)",
    FEAT_EXTRA_DISPLAY = "Mostrar los botones extra junto a la barra de acción del mando",
    MAP_IDENTIFY = "Identificar las paletas traseras",
    MAP_IDENTIFY_HINT = "Pulsa cada paleta trasera cuando se te pida, para que el addon sepa qué tecla o botón envía (asigna antes teclas del teclado a las paletas en Steam Input).",
    MAP_PLACE = "Colocar la barra y los botones",
    MAP_PLACE_HINT = "Mueve la barra del mando del juego por pasos y coloca cada botón extra (paletas, L3, R3) a su alrededor, directamente en la pantalla.",
    MAP_WIZARD = "Pulsa ahora la paleta %s.",
    MAP_WIZARD_DONE = "Paletas traseras identificadas.",
    MAP_P_SKIP = "Saltar",
    MAP_P_SECTION = "Sección",
    MAP_P_LIST = "Lista",
    PLACE_TITLE = "Colocar la barra y los botones",
    PLACE_P_BUTTON = "Elemento",
    PLACE_P_SYM = "Simetría: %s",
    PLACE_P_RESET = "Sitio por defecto",
    PLACE_P_DONE = "Terminar",
    BINDING_CONFIG = "Configuración de Controller Keyboard",
    MOD_MAPPING = "Mando: funciones extra en los botones libres y las paletas traseras",
    MAP_TITLE = "Asignación del mando",
    MAP_ALONE = "Solo",
    MAP_FREE = "Libre",
    MAP_GAME = "Juego",
    MAP_EMPTY_SLOT = "vacío",
    MAP_BACK_ROW = "Paletas traseras",
    MAP_LOCKED = "Aquí no hay capa: este gatillo no es un modificador en los ajustes del mando del juego, el botón hace lo mismo que sin él.",
    MAP_NATIVE_HINT = "Función fija del juego, se queda como está.",
    MAP_FREE_HINT = "Libre: A para darle una función.",
    MAP_ASSIGNED_HINT = "Añadido por Controller Keyboard (X para quitar).",
    MAP_PADDLE_KEY = "Tecla de la paleta: %s (Y para aprenderla de nuevo)",
    MAP_PADDLE_PRESS = "Pulsa ahora la paleta... (B para cancelar)",
    MAP_NOTHING = "Nada aquí",
    MAP_TAB_GAME = "Juego",
    MAP_TAB_SPELLS = "Hechizos",
    MAP_TAB_ITEMS = "Objetos",
    MAP_TAB_MACROS = "Macros",
    MAP_TAB_BAR = "Barra",
    MAP_P_MOVE = "Mover",
    MAP_P_CHOOSE = "Elegir",
    MAP_P_CLEAR = "Quitar",
    MAP_P_KEY = "Tecla de paleta",
    MAP_P_LAYER = "Capa",
    MAP_P_CLOSE = "Cerrar",
    MAP_P_BACK = "Volver",
    MAP_P_TAB = "Pestaña",
    NAT_JUMP = "Saltar",
    NAT_INTERACT = "Interactuar",
    NAT_BACK = "Volver",
    NAT_INSPECT = "Inspeccionar",
    NAT_TARGET_FRIEND = "Seleccionar aliados",
    NAT_TARGET_ENEMY = "Seleccionar enemigos",
    NAT_LAYER_LEFT = "Barra izquierda",
    NAT_LAYER_RIGHT = "Barra derecha",
    NAT_START = "Menú Start",
    NAT_SELECT = "Foco de la interfaz",
    NAT_PING = "Ping",
    BINDING_MAP = "Asignación del mando",
    PADDLE_KEY_REPLACES = "%s estaba asignada a «%s»: la paleta la sustituye.",
    CAT_COMMON = "Atajos habituales",
    DETECT_START = "Pulsa ahora cada paleta trasera (L4, R4, L5, R5): las teclas recibidas se muestran durante %d segundos.",
    DETECT_KEY = "Tecla recibida: %s",
    DETECT_PAD = "Botón del mando recibido: %s",
    DETECT_END = "Detección de teclas terminada.",
    QUEST_ITEM_TIP = "Objeto de misión: no vender",
    QUEST_ITEM_SOLD = "Objeto de misión vendido: %s. Recómpralo en la pestaña Recomprar del vendedor.",
    QUEST_ITEM_SOLD_SHORT = "¡Objeto de misión vendido! Mira la pestaña Recomprar",
    NO_QUESTS = "Ninguna misión en curso",
    QUESTS_TIP = "Misiones: insertar un enlace de misión",
    KEYBOARD_OFF = "El teclado está desactivado (Opciones > AddOns > Controller Keyboard > Módulos).",
    MOD_KEYBOARD = "Teclado (daisywheel / teclado dividido)",
    MOD_QUEST_ITEMS = "Objetos de misión: «no vender» en las descripciones, aviso en el vendedor",
    MOD_QUEST_LINKS = "Enlaces de misión en el teclado (y enlaces con Mayús+clic)",
}
LOCALES.esMX = LOCALES.esES

LOCALES.itIT = {
    SHIFT = "Maiusc",
    SPACE = "Spazio",
    BACKSPACE = "Cancella",
    SEND = "Invia",
    SEND_COMBAT = "Tastiera aperta in combattimento: premi Invio per inviare.",
    DRAG_HINT = "Trascina per spostare la tastiera (/ck lock per bloccarla)",
    LOCKED = "Posizione bloccata: %s",
    TEXTURES_MISSING = "|cffff4040Texture non trovate|r: chiudi e riavvia il gioco (/reload non basta per i nuovi file).",
    COMBAT_UNAVAILABLE = "Impossibile in combattimento",
    HELP_PETAL = "Petalo",
    HELP_LETTER = "Lettera",
    HELP_CHANNEL = "Canale",
    HELP_PICK = "Scegli",
    HELP_CURSOR_L = "Cursore sx",
    HELP_CURSOR_R = "Cursore dx",
    HELP_TYPE_L = "Scrivi sx",
    HELP_TYPE_R = "Scrivi dx",
    OPT_INPUT = "Scrittura",
    OPT_METHOD = "Metodo di scrittura",
    METHOD_STICK = "Tastiera divisa",
    OPT_LAYOUT = "Layout (tastiera divisa)",
    OPT_DEADZONE = "Zona morta dello stick",
    OPT_MAGNET = "Effetto calamita",
    OPT_CURVE = "Risposta dello stick",
    CURVE_LINEAR = "Lineare",
    CURVE_GENTLE = "Morbida (precisa al centro)",
    CURVE_FAST = "Rapida",
    MAGNET_NONE = "Nessuno",
    MAGNET_WEAK = "Debole",
    MAGNET_MEDIUM = "Medio",
    MAGNET_STRONG = "Forte",
    OPT_LINE = "Mostra la linea del cursore",
    MODE_SET = "Metodo di scrittura: %s",
    LAYOUT_SET = "Layout: %s",
    LANG_SET = "Lingua: %s",
    REPLY_TO = "Rispondi a %s: ",
    WHISPER_NAME = "Sussurra a (nome, poi A): ",
    CHANNEL_NAMES = { "Parla", "Urla", "Gruppo", "Incursione", "Gilda", "Generale (/1)", "Sussurra", "Rispondi" },
    CHANNEL_UNAVAILABLE = "non disponibile",
    BADGE_SHIFT = "MAIUSC",
    BADGE_CAPS = "BLOC MAIUSC",
    FONT_CHAT = "Carattere della chat",
    GLYPHS_NONE = "Nessuna icona dei pulsanti del controller trovata: vengono usate quelle dell'addon.",
    GLYPHS_FOUND = "%d icone dei pulsanti del controller trovate:",
    OPT_SUBTITLE = "Tastiera su schermo per scrivere in chat con il controller o il mouse.",
    OPT_KEYBOARD = "Tastiera",
    OPT_LOCK = "Blocca la posizione",
    OPT_AUTO = "Apri automaticamente con la chat",
    OPT_PAD_ONLY = "Solo quando il controller è attivo",
    OPT_INVERT = "Inverti l'asse verticale degli stick",
    OPT_SCALE = "Dimensione della tastiera",
    SIZE_SMALL = "Piccola",
    SIZE_NORMAL = "Normale",
    SIZE_LARGE = "Grande",
    SIZE_XL = "Molto grande",
    OPT_ACTIONS = "Mostra i pulsanti del mouse (Maiusc, 123, Spazio, Cancella, Invia, X)",
    OPT_STICKY = "Il canale scelto diventa quello della chat (come scrivere /p nel gioco)",
    OPT_LOOK = "Aspetto",
    OPT_FONT = "Carattere",
    OPT_GLYPHS = "Icone dei pulsanti",
    OPT_GAME_GLYPHS = "Usa le icone dei pulsanti del gioco se disponibili",
    OPT_PREDICTION = "Previsione",
    OPT_LANG = "Lingua dei suggerimenti",
    OPT_LEARN = "Impara dai miei messaggi",
    OPT_RESET_POS = "Riposiziona la tastiera",
    OPT_FORGET = "Dimentica le parole apprese",
    OPT_FORGET_CONFIRM = "Clicca di nuovo per confermare",
    LOADED = "v%s caricato. /ck per l'aiuto.",
    HELP = {
        "/ck - apri la tastiera",
        "/ck auto - apri automaticamente con la chat (attuale: %s)",
        "/ck pad - apri automaticamente solo se il controller è attivo (attuale: %s)",
        "/ck learn - impara le parole dai tuoi messaggi (attuale: %s)",
        "/ck lock - blocca/sblocca la posizione (attuale: %s)",
        "/ck mode wheel|stick - daisywheel o tastiera divisa",
        "/ck layout azerty|qwerty|qwertz|es|it - layout della tastiera divisa",
        "/ck lang fr|en|de|es|it|both - lingua dei suggerimenti e degli accenti",
        "/ck scale 0.8 - dimensione della tastiera",
        "/ck invert - inverti l'asse verticale dello stick",
        "/ck reset - riposiziona la tastiera",
        "/ck stats - statistiche di apprendimento",
        "/ck forget - dimentica tutte le parole apprese",
        "/ck glyphs - elenca le icone dei pulsanti del controller del gioco",
        "/ck config - configurazione (anche RB + croce giù)",
        "/ck map - mappatura del controller (pulsanti liberi, levette)",
        "/ck keys - mostra i tasti ricevuti dal gioco (levette)",
        "/ck debug - mostra i pulsanti ricevuti",
        "Opzioni: Esc > Opzioni > AddOns > Controller Keyboard",
    },
    ON = "|cff40ff40sì|r",
    OFF = "|cffff4040no|r",
    STATS = "%d parole apprese, %d parole nel dizionario.",
    FORGOT = "Parole apprese cancellate.",
    FORGET_CONFIRM = "Scrivi /ck forget confirm per cancellare tutte le parole apprese.",
    NO_DICT = "Dizionario non disponibile: %s",
    BINDING_TOGGLE = "Mostra/nascondi la tastiera",
    BADGE_HIDDEN = "Nascosto",
    BADGE_RIGHT = "A destra",
    BADGE_LEFT = "A sinistra",
    BADGE_BOTTOM = "Sotto",
    BADGE_TOP = "Sopra",
    BADGE_OUTER = "Lato esterno",
    OPT_BADGE = "Nome dei pulsanti extra (R4...)",
    PLACE_MOVING = "in spostamento",
    PLACE_P_CANCEL = "Annulla",
    PLACE_P_DROP = "Posa",
    PLACE_P_GRAB = "Prendi",
    PLACE_P_SELECT = "Scegli",
    MAP_SLOT_HINT = "Casella della barra del controller del gioco: A per metterci un incantesimo, un oggetto o una macro (come l'editor del gioco), X per svuotarla.",
    FEAT_RT_MODIFIER = "RT funge da modificatore: livelli RT e LT + RT per i pulsanti extra",
    FEAT_RT_MODIFIER_TIP = "Imposta l'opzione del controller del gioco «RT emula Alt» (o Ctrl), come LT invia già Maiusc: RT + una levetta diventa un tasto a sé. La barra RT del gioco continua a funzionare.",
    FEAT_QUEST_GLOW = "Bagliore arancione attorno agli oggetti di missione nelle borse",
    MAP_P_CONFIRM = "Conferma",
    PLACE_BAR = "Barra del controller",
    PLACE_P_PLACE = "Posto",
    FEAT_SHOW_STICKS = "Mostra L3 e R3 accanto alla barra, con la loro azione (corsa automatica, ping...)",
    FEAT_SHORTCUT = "Scorciatoia del controller per aprire questo pannello",
    CFG_SHORTCUT_KEY = "Combinazione: %s (A per cambiarla)",
    CFG_SHORTCUT_PRESS = "Tieni premuto un pulsante e premine un secondo... (Esc o B da solo: annulla)",
    CFG_SHORTCUT_RESET = "Torna a %s",
    CFG_TAB_GENERAL = "Generale",
    CFG_TAB_KEYBOARD = "Tastiera",
    CFG_TAB_GAMEPAD = "Controller",
    CFG_P_CHANGE = "Cambia",
    CFG_OPEN = "Apri la configurazione",
    CFG_OPEN_LATER = "Il pannello di Controller Keyboard si aprirà quando torni in gioco (opzioni e menu di gioco chiusi).",
    CFG_SETTINGS_HINT = "Tutte le impostazioni sono nel pannello dell'addon, con il controller o il mouse: RB + croce giù, /ck config o la sua scorciatoia.",
    CFG_H_FEATURES = "Funzioni",
    FEAT_DRAFTS = "Tieni il messaggio come bozza quando il gioco chiude la chat",
    FEAT_LINKS = "Aggiungi al messaggio i link di Maiusc+clic e «Condividi nella chat»",
    FEAT_QUEST_TOOLTIP = "Riga arancione «non vendere» nei tooltip",
    FEAT_QUEST_SELL = "Avviso quando si vende un oggetto di missione",
    FEAT_QUEST_HOVER = "Avviso selezionando un oggetto di missione da un mercante (borse del controller senza tooltip)",
    FEAT_EXTRA_DISPLAY = "Mostra i pulsanti extra accanto alla barra delle azioni del controller",
    MAP_IDENTIFY = "Identifica le levette posteriori",
    MAP_IDENTIFY_HINT = "Premi ogni levetta posteriore quando richiesto, così l'addon sa quale tasto o pulsante invia (assegna prima dei tasti della tastiera alle levette in Steam Input).",
    MAP_PLACE = "Posiziona barra e pulsanti",
    MAP_PLACE_HINT = "Sposta a scatti la barra del controller del gioco e posiziona ogni pulsante extra (levette, L3, R3) intorno, direttamente sullo schermo.",
    MAP_WIZARD = "Premi ora la levetta %s.",
    MAP_WIZARD_DONE = "Levette posteriori identificate.",
    MAP_P_SKIP = "Salta",
    MAP_P_SECTION = "Sezione",
    MAP_P_LIST = "Elenco",
    PLACE_TITLE = "Posiziona barra e pulsanti",
    PLACE_P_BUTTON = "Elemento",
    PLACE_P_SYM = "Simmetria: %s",
    PLACE_P_RESET = "Posto predefinito",
    PLACE_P_DONE = "Fine",
    BINDING_CONFIG = "Configurazione di Controller Keyboard",
    MOD_MAPPING = "Controller: funzioni extra sui pulsanti liberi e sulle levette posteriori",
    MAP_TITLE = "Mappatura del controller",
    MAP_ALONE = "Da solo",
    MAP_FREE = "Libero",
    MAP_GAME = "Gioco",
    MAP_EMPTY_SLOT = "vuoto",
    MAP_BACK_ROW = "Levette posteriori",
    MAP_LOCKED = "Nessun livello qui: questo grilletto non è un modificatore nelle impostazioni del controller del gioco, il pulsante fa lo stesso che senza.",
    MAP_NATIVE_HINT = "Funzione fissa del gioco, resta com'è.",
    MAP_FREE_HINT = "Libero: A per dargli una funzione.",
    MAP_ASSIGNED_HINT = "Aggiunto da Controller Keyboard (X per rimuovere).",
    MAP_PADDLE_KEY = "Tasto della levetta: %s (Y per impararlo di nuovo)",
    MAP_PADDLE_PRESS = "Premi ora la levetta... (B per annullare)",
    MAP_NOTHING = "Niente qui",
    MAP_TAB_GAME = "Gioco",
    MAP_TAB_SPELLS = "Incantesimi",
    MAP_TAB_ITEMS = "Oggetti",
    MAP_TAB_MACROS = "Macro",
    MAP_TAB_BAR = "Barra",
    MAP_P_MOVE = "Muovi",
    MAP_P_CHOOSE = "Scegli",
    MAP_P_CLEAR = "Rimuovi",
    MAP_P_KEY = "Tasto levetta",
    MAP_P_LAYER = "Livello",
    MAP_P_CLOSE = "Chiudi",
    MAP_P_BACK = "Indietro",
    MAP_P_TAB = "Scheda",
    NAT_JUMP = "Salta",
    NAT_INTERACT = "Interagisci",
    NAT_BACK = "Indietro",
    NAT_INSPECT = "Ispeziona",
    NAT_TARGET_FRIEND = "Bersaglia alleati",
    NAT_TARGET_ENEMY = "Bersaglia nemici",
    NAT_LAYER_LEFT = "Barra sinistra",
    NAT_LAYER_RIGHT = "Barra destra",
    NAT_START = "Menu Start",
    NAT_SELECT = "Focus dell'interfaccia",
    NAT_PING = "Ping",
    BINDING_MAP = "Mappatura del controller",
    PADDLE_KEY_REPLACES = "%s era assegnato a «%s»: la levetta lo sostituisce.",
    CAT_COMMON = "Scorciatoie comuni",
    DETECT_START = "Premi ora ogni levetta posteriore (L4, R4, L5, R5): i tasti ricevuti vengono mostrati per %d secondi.",
    DETECT_KEY = "Tasto ricevuto: %s",
    DETECT_PAD = "Pulsante del controller ricevuto: %s",
    DETECT_END = "Rilevamento dei tasti terminato.",
    QUEST_ITEM_TIP = "Oggetto di missione: non vendere",
    QUEST_ITEM_SOLD = "Oggetto di missione venduto: %s. Ricompralo nella scheda Riacquista del mercante.",
    QUEST_ITEM_SOLD_SHORT = "Oggetto di missione venduto! Vedi Riacquista",
    NO_QUESTS = "Nessuna missione in corso",
    QUESTS_TIP = "Missioni: inserisci un link di missione",
    KEYBOARD_OFF = "La tastiera è disattivata (Opzioni > AddOns > Controller Keyboard > Moduli).",
    MOD_KEYBOARD = "Tastiera (daisywheel / tastiera divisa)",
    MOD_QUEST_ITEMS = "Oggetti di missione: «non vendere» nei tooltip, avviso dal mercante",
    MOD_QUEST_LINKS = "Link di missione nella tastiera (e link con Maiusc+clic)",
}

for key, value in pairs(LOCALES[GetLocale()] or {}) do
    L[key] = value
end

BINDING_HEADER_CONTROLLERKEYBOARD = "Controller Keyboard"
BINDING_NAME_CONTROLLERKEYBOARD_TOGGLE = L.BINDING_TOGGLE
BINDING_NAME_CONTROLLERKEYBOARD_MAP = L.BINDING_MAP
BINDING_NAME_CONTROLLERKEYBOARD_CONFIG = L.BINDING_CONFIG

---------------------------------------------------------------------------
-- Saved variables
---------------------------------------------------------------------------
CK.DEFAULT_SHORTCUT = { hold = "PADRSHOULDER", press = "PADDDOWN" }

local DEFAULTS = {
    autoOpen = true,
    onlyWithGamepad = false,
    learn = true,
    -- Suggestions and keyboard layout follow the client's language by default
    lang = ({ frFR = "fr", deDE = "de", esES = "es", esMX = "es", itIT = "it" })[GetLocale()] or "en",
    maxWords = 8000,
    numSuggestions = 5,
    scale = 1,
    invertY = false,
    locked = true,
    -- Modules, each one can be turned off
    modules = { keyboard = true, questItems = true, questLinks = true, mapping = true },
    -- Gamepad mapping: ["L3:LT"] = "cmd:TOGGLERUN" | "spell:133" | "item:5512" | "macro:Name" | "bar:bottom:a"
    mapping = {},
    -- Back paddles' learned keys: { key = "F13" }
    paddles = { L4 = {}, L5 = {}, R4 = {}, R5 = {} },
    -- Each function can be turned off (General tab)
    features = {
        drafts = true, linkCapture = true,
        questTooltip = true, questGlow = true, questSellAlert = true, questHoverAlert = true,
        extraDisplay = true, showSticks = true, configShortcut = true,
    },
    -- Extra buttons' places ({ x, y } from the game's left / right bar), mirrored
    extraPos = {},
    -- The game's gamepad bar, moved by steps (0, 0: the game's own place)
    barOffset = { x = 0, y = 0 },
    -- The configuration panel's shortcut: a button held, another pressed
    shortcut = { hold = "PADRSHOULDER", press = "PADDDOWN" },
    extraSymmetric = true,
    badgePlace = "outer",    -- "R4" on the extra buttons: outer / top / bottom / left / right / hidden
    inputMethod = "wheel",   -- "wheel" (daisywheel) or "stick" (split keyboard)
    kbLayout = ({ frFR = "azerty", deDE = "qwertz", esES = "qwerty_es", esMX = "qwerty_es",
        itIT = "qwerty_it" })[GetLocale()] or "qwerty",
    deadzone = 0.15,         -- split keyboard: sticks dead zone
    stickCurve = "linear",   -- split keyboard: linear / gentle / fast
    magnet = "medium",       -- split keyboard: none / weak / medium / strong
    showLine = true,         -- split keyboard: lines from the centers to the cursors
    showActions = true,
    stickyChannel = true,    -- the channel row also sets the chat's own sticky channel
    font = "friz",
    glyphStyle = "xbox",
    gameGlyphs = true,
    debug = false,
}

local function copyDefaults(src, dst)
    for k, v in pairs(src) do
        if type(v) == "table" then
            if type(dst[k]) ~= "table" then dst[k] = {} end
            copyDefaults(v, dst[k])
        elseif dst[k] == nil then
            dst[k] = v
        end
    end
end

function CK:InitDB()
    ControllerKeyboardDB = ControllerKeyboardDB or {}
    local db = ControllerKeyboardDB
    db.settings = db.settings or {}
    -- Before 0.4.2: dicts = { frFR = bool, enUS = bool } instead of a language
    if db.settings.lang == nil and type(db.settings.dicts) == "table" then
        local d = db.settings.dicts
        db.settings.lang = (d.frFR and d.enUS) and "fren" or (d.enUS and "en") or "fr"
    end
    copyDefaults(DEFAULTS, db.settings)
    -- v2: auto-open no longer requires the gamepad to be the active input
    if (db.version or 1) < 2 then
        db.settings.onlyWithGamepad = false
        db.pos = nil
        db.version = 2
    end
    self.db = db
    self:ApplyLanguage()
    db.words = db.words or {}
    db.commands = db.commands or {}
    db.trigrams = db.trigrams or {}
    db.starts = db.starts or {}
    db.bigrams = db.bigrams or {}
    self.db = db
end

function CK:Print(msg, ...)
    if select("#", ...) > 0 then msg = format(msg, ...) end
    DEFAULT_CHAT_FRAME:AddMessage("|cff33ccffController Keyboard|r: " .. tostring(msg))
end

---------------------------------------------------------------------------
-- UTF-8 helpers (French accents)
---------------------------------------------------------------------------
local UTF8_2 = "[\195\197][\128-\191]"

local LOWER = {
    ["À"] = "à", ["Â"] = "â", ["Ä"] = "ä", ["Á"] = "á", ["Ç"] = "ç", ["É"] = "é", ["È"] = "è",
    ["Ê"] = "ê", ["Ë"] = "ë", ["Î"] = "î", ["Ï"] = "ï", ["Í"] = "í", ["Ô"] = "ô", ["Ö"] = "ö",
    ["Ó"] = "ó", ["Ò"] = "ò", ["Ì"] = "ì", ["Ù"] = "ù", ["Û"] = "û", ["Ü"] = "ü", ["Ú"] = "ú", ["Ÿ"] = "ÿ", ["Ñ"] = "ñ",
    ["Œ"] = "œ", ["Æ"] = "æ",
}
local UPPER = {}
for up, low in pairs(LOWER) do UPPER[low] = up end

local STRIP = {
    ["à"] = "a", ["â"] = "a", ["ä"] = "a", ["á"] = "a", ["ç"] = "c", ["é"] = "e", ["è"] = "e",
    ["ê"] = "e", ["ë"] = "e", ["î"] = "i", ["ï"] = "i", ["í"] = "i", ["ô"] = "o", ["ö"] = "o",
    ["ó"] = "o", ["ò"] = "o", ["ì"] = "i", ["ß"] = "ss", ["ù"] = "u", ["û"] = "u", ["ü"] = "u", ["ú"] = "u", ["ÿ"] = "y", ["ñ"] = "n",
    ["œ"] = "oe", ["æ"] = "ae",
}

-- string.lower/upper may touch UTF-8 bytes depending on the C locale: only map A-Z
local ASCII_LOWER, ASCII_UPPER = {}, {}
for b = 65, 90 do
    ASCII_LOWER[string.char(b)] = string.char(b + 32)
    ASCII_UPPER[string.char(b + 32)] = string.char(b)
end

function CK.Lower(s)
    return (s:gsub("[A-Z]", ASCII_LOWER):gsub(UTF8_2, LOWER))
end

function CK.Upper(s)
    return (s:gsub("[a-z]", ASCII_UPPER):gsub(UTF8_2, UPPER))
end

-- Lowercase and strip accents: "Été" -> "ete"
function CK.Normalize(s)
    return (CK.Lower(s):gsub(UTF8_2, STRIP))
end

function CK.FirstChar(s)
    return s:match("^[\192-\255][\128-\191]*") or s:sub(1, 1)
end

function CK.IsUpperInitial(s)
    local c = CK.FirstChar(s)
    return c ~= "" and c ~= CK.Lower(c)
end

function CK.Capitalize(s)
    local c = CK.FirstChar(s)
    return CK.Upper(c) .. s:sub(#c + 1)
end

---------------------------------------------------------------------------
-- Languages: dictionaries, and the accents of the 123 layer
---------------------------------------------------------------------------
CK.LANGUAGES = {
    { key = "fr", name = "Français", dicts = { "frFR" }, accents = "fr" },
    { key = "en", name = "English", dicts = { "enUS" }, accents = "en" },
    { key = "de", name = "Deutsch", dicts = { "deDE" }, accents = "de" },
    { key = "es", name = "Español", dicts = { "esES" }, accents = "es" },
    { key = "it", name = "Italiano", dicts = { "itIT" }, accents = "it" },
    { key = "fren", name = "Français + English", dicts = { "frFR", "enUS" }, accents = "fr" },
}

-- 12 characters per language: the accents first, then useful punctuation
CK.ACCENTS = {
    fr = { "é", "è", "ê", "à", "â", "ç", "ù", "û", "î", "ô", "ë", "ï" },
    en = { "é", "è", "à", "ç", "'", "?", "!", "-", "&", "$", "ë", "ï" },
    de = { "ä", "ö", "ü", "ß", "?", "!", "'", "-", "€", "&", "§", "_" },
    es = { "á", "é", "í", "ó", "ú", "ñ", "ü", "¿", "¡", "'", "-", "ç" },
    it = { "à", "è", "é", "ì", "ò", "ù", "ó", "í", "ú", "'", "?", "!" },
}

function CK:GetLanguage()
    local key = self.db and self.db.settings.lang
    for _, lang in ipairs(CK.LANGUAGES) do
        if lang.key == key then return lang end
    end
    return CK.LANGUAGES[2]
end

function CK:Accents()
    return CK.ACCENTS[self:GetLanguage().accents] or CK.ACCENTS.fr
end

-- The dictionaries in use come from the language
function CK:ApplyLanguage()
    local dicts = {}
    for _, key in ipairs(self:GetLanguage().dicts) do dicts[key] = true end
    self.db.settings.dicts = dicts
end

function CK:SetLanguage(key)
    self.db.settings.lang = key
    self:ApplyLanguage()
    CK.Predict:Load()
    if self.frame then self:UpdateMethod() end
end

-- Remove the last UTF-8 character of a string
function CK.DropLastChar(s)
    local i = #s
    while i > 1 do
        local b = s:byte(i)
        if b < 128 or b >= 192 then break end
        i = i - 1
    end
    return s:sub(1, i - 1)
end

-- Letters (ASCII + any UTF-8 byte) form words
CK.WORD_CHARS = "[%a\128-\255]"
