local _, CK = ...
CK.NextWords = CK.NextWords or {}

-- Enchaînements courants du français parlé / chat, pour la prédiction du mot
-- suivant avant que l'addon ait appris les habitudes du joueur.
-- starts : débuts de message. next[mot] : mots suivants, du plus probable au moins probable.
-- Les élisions sont des mots à part entière : "j'" -> "ai", "c'" -> "est".
CK.NextWords.frFR = {
    starts = [[
salut slt cc bonjour bonsoir merci ok oui non je j' tu on ça c' gg lfg lfm il qui
quelqu'un désolé dsl bon bonne inv yo hello mdr ah oh bah bien pas
]],
    next = {
        ["je"] = "suis vais pense sais peux veux crois dois te me ne cherche reviens",
        ["j'"] = "ai arrive aime avais attends étais adore y irai",
        ["tu"] = "es as veux peux vas fais sais viens me te connais",
        ["t'"] = "es as étais inquiète",
        ["il"] = "y est faut a va fait me était manque reste",
        ["elle"] = "est a va fait était",
        ["on"] = "va peut fait se y est a part pull attend",
        ["nous"] = "sommes avons allons pouvons",
        ["vous"] = "êtes avez pouvez voulez allez faites",
        ["ils"] = "sont ont vont",
        ["c'"] = "est était",
        ["ça"] = "va marche fait me te y dépend",
        ["est"] = "pas bon bien là un une en où",
        ["suis"] = "là en pas désolé prêt dispo occupé afk de",
        ["es"] = "où là dispo prêt sûr",
        ["as"] = "besoin vu fait le pas",
        ["ai"] = "pas besoin fini un une été vu rien",
        ["vais"] = "faire aller y te me bientôt",
        ["va"] = "y faire bien être se",
        ["veux"] = "bien pas faire venir",
        ["peux"] = "pas me te venir",
        ["peut"] = "être faire aller",
        ["faut"] = "que pas le un",
        ["merci"] = "beaucoup pour à bien",
        ["bonne"] = "nuit soirée journée chance",
        ["bon"] = "courage jeu ben appétit",
        ["à"] = "plus demain toute bientôt la tout",
        ["a"] = "plus demain",
        ["de"] = "rien la le ma mon",
        ["pour"] = "le la les moi toi un une",
        ["pas"] = "de mal le la encore",
        ["qui"] = "est veut peut",
        ["que"] = "je tu il on ça",
        ["qu'"] = "il on elle",
        ["n'"] = "est ai as importe",
        ["d'"] = "accord abord",
        ["l'"] = "instance heure",
        ["s'"] = "il",
        ["m'"] = "a",
        ["dans"] = "le la les",
        ["en"] = "train fait plus",
        ["un"] = "peu groupe tank heal instant",
        ["une"] = "minute seconde quête",
        ["le"] = "groupe tank heal boss",
        ["la"] = "quête guilde",
        ["les"] = "gars mobs",
        ["avec"] = "toi moi vous",
        ["y"] = "a aller",
        ["oui"] = "je merci ok",
        ["non"] = "merci je pas",
        ["ok"] = "je merci on",
        ["salut"] = "les tout ça",
        ["slt"] = "les ça",
        ["bonjour"] = "à tout",
        ["cherche"] = "un une groupe tank heal",
        ["besoin"] = "d' de",
        ["lfg"] = "tank heal dps",
        ["lfm"] = "tank heal dps",
        ["inv"] = "pls stp",
        ["gg"] = "wp à",
        ["tout"] = "le de va",
        ["très"] = "bien",
        ["trop"] = "bien cool",
        ["bien"] = "joué sûr vu",
        ["pk"] = "pas",
        ["stp"] = "merci",
        ["comment"] = "ça tu",
        ["où"] = "est es tu",
        ["quoi"] = "de",
        ["quand"] = "tu on",
    },
}
