"""Build Dict_<locale>.lua from a word frequency list.

Default source: hermitdave/FrequencyWords (OpenSubtitles 2018, CC-BY-SA-4.0),
a list of "word count" lines sorted by frequency.

Usage:
    python tools/build_dict.py fr            # downloads fr_50k.txt -> Dict_frFR.lua
    python tools/build_dict.py en            # downloads en_50k.txt -> Dict_enUS.lua
    python tools/build_dict.py de|es|it      # German, Spanish, Italian
    python tools/build_dict.py fr --input my_list.txt --size 15000
"""
import argparse
import re
import urllib.request
from pathlib import Path

SOURCE = "https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018/{lang}/{lang}_50k.txt"
LOCALES = {"fr": "frFR", "en": "enUS", "de": "deDE", "es": "esES", "it": "itIT"}
LETTERS = "a-zàâäáçéèêëîïíìôöóòùûüúÿñœæß"
WORD = re.compile(rf"^[{LETTERS}]+(['-][{LETTERS}]+)*$")
# Real one-letter words; other single letters are noise
SINGLE = {
    "fr": {"a", "à", "y"},
    "en": {"a", "i"},
    "de": set(),
    "es": {"a", "y", "o", "e", "u"},
    "it": {"a", "e", "o", "è", "i"},
}
ROOT = Path(__file__).resolve().parent.parent


def load(lang, input_path):
    if input_path:
        return Path(input_path).read_text(encoding="utf-8").splitlines()
    url = SOURCE.format(lang=lang)
    print(f"Downloading {url}")
    with urllib.request.urlopen(url) as r:
        return r.read().decode("utf-8").splitlines()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("lang", choices=sorted(LOCALES))
    ap.add_argument("--input", help="local frequency list (one 'word [count]' per line)")
    ap.add_argument("--size", type=int, default=12000)
    args = ap.parse_args()

    words, seen = [], set()
    for line in load(args.lang, args.input):
        parts = line.split()
        if not parts:
            continue
        w = parts[0].lower()
        if w in seen or not WORD.match(w):
            continue
        # single letters are noise, except real one-letter words
        if len(w) == 1 and w not in SINGLE[args.lang]:
            continue
        seen.add(w)
        words.append(w)
        if len(words) >= args.size:
            break

    locale = LOCALES[args.lang]
    lines, line = [], ""
    for w in words:
        if len(line) + len(w) + 1 > 100:
            lines.append(line)
            line = ""
        line = f"{line} {w}" if line else w
    if line:
        lines.append(line)

    out = ROOT / f"Dict_{locale}.lua"
    body = "\n".join(lines)
    out.write_text(
        "local _, CK = ...\n"
        "CK.Dicts = CK.Dicts or {}\n\n"
        f"-- {len(words)} words sorted by frequency. Generated by tools/build_dict.py\n"
        "-- Source: FrequencyWords (hermitdave), OpenSubtitles 2018, CC-BY-SA-4.0\n"
        f"CK.Dicts.{locale} = [[\n{body}\n]]\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(words)} words to {out.name}")


if __name__ == "__main__":
    main()
